/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  OEmbedResponseModel,
} from '../models/index';
import {
    OEmbedResponseModelFromJSON,
    OEmbedResponseModelToJSON,
} from '../models/index';

export interface GetOembedQueryRequest {
    url?: string;
    maxWidth?: number;
    maxHeight?: number;
}

/**
 * 
 */
export class OEmbedApi extends runtime.BaseAPI {

    /**
     */
    async getOembedQueryRaw(requestParameters: GetOembedQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OEmbedResponseModel>> {
        const queryParameters: any = {};

        if (requestParameters['url'] != null) {
            queryParameters['url'] = requestParameters['url'];
        }

        if (requestParameters['maxWidth'] != null) {
            queryParameters['maxWidth'] = requestParameters['maxWidth'];
        }

        if (requestParameters['maxHeight'] != null) {
            queryParameters['maxHeight'] = requestParameters['maxHeight'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Backoffice User", []);
        }

        const response = await this.request({
            path: `/umbraco/management/api/v1/oembed/query`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OEmbedResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async getOembedQuery(requestParameters: GetOembedQueryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OEmbedResponseModel> {
        const response = await this.getOembedQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
