/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetItemRelationType200ResponseInner,
  PagedRelationTypeResponseModel,
  ProblemDetails,
  RelationTypeResponseModel,
} from '../models/index';
import {
    GetItemRelationType200ResponseInnerFromJSON,
    GetItemRelationType200ResponseInnerToJSON,
    PagedRelationTypeResponseModelFromJSON,
    PagedRelationTypeResponseModelToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    RelationTypeResponseModelFromJSON,
    RelationTypeResponseModelToJSON,
} from '../models/index';

export interface GetItemRelationTypeRequest {
    id?: Set<string>;
}

export interface GetRelationTypeRequest {
    skip?: number;
    take?: number;
}

export interface GetRelationTypeByIdRequest {
    id: string;
}

/**
 * 
 */
export class RelationTypeApi extends runtime.BaseAPI {

    /**
     */
    async getItemRelationTypeRaw(requestParameters: GetItemRelationTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetItemRelationType200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Backoffice User", []);
        }

        const response = await this.request({
            path: `/umbraco/management/api/v1/item/relation-type`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetItemRelationType200ResponseInnerFromJSON));
    }

    /**
     */
    async getItemRelationType(requestParameters: GetItemRelationTypeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetItemRelationType200ResponseInner>> {
        const response = await this.getItemRelationTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRelationTypeRaw(requestParameters: GetRelationTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedRelationTypeResponseModel>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Backoffice User", []);
        }

        const response = await this.request({
            path: `/umbraco/management/api/v1/relation-type`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedRelationTypeResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async getRelationType(requestParameters: GetRelationTypeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedRelationTypeResponseModel> {
        const response = await this.getRelationTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRelationTypeByIdRaw(requestParameters: GetRelationTypeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelationTypeResponseModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRelationTypeById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Backoffice User", []);
        }

        const response = await this.request({
            path: `/umbraco/management/api/v1/relation-type/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationTypeResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async getRelationTypeById(requestParameters: GetRelationTypeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelationTypeResponseModel> {
        const response = await this.getRelationTypeByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
