/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvailableMediaTypeCompositionResponseModel
 */
export interface AvailableMediaTypeCompositionResponseModel {
    /**
     * 
     * @type {string}
     * @memberof AvailableMediaTypeCompositionResponseModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AvailableMediaTypeCompositionResponseModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AvailableMediaTypeCompositionResponseModel
     */
    icon: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AvailableMediaTypeCompositionResponseModel
     */
    folderPath: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AvailableMediaTypeCompositionResponseModel
     */
    isCompatible: boolean;
}

/**
 * Check if a given object implements the AvailableMediaTypeCompositionResponseModel interface.
 */
export function instanceOfAvailableMediaTypeCompositionResponseModel(value: object): value is AvailableMediaTypeCompositionResponseModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('folderPath' in value) || value['folderPath'] === undefined) return false;
    if (!('isCompatible' in value) || value['isCompatible'] === undefined) return false;
    return true;
}

export function AvailableMediaTypeCompositionResponseModelFromJSON(json: any): AvailableMediaTypeCompositionResponseModel {
    return AvailableMediaTypeCompositionResponseModelFromJSONTyped(json, false);
}

export function AvailableMediaTypeCompositionResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailableMediaTypeCompositionResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'icon': json['icon'],
        'folderPath': json['folderPath'],
        'isCompatible': json['isCompatible'],
    };
}

export function AvailableMediaTypeCompositionResponseModelToJSON(json: any): AvailableMediaTypeCompositionResponseModel {
    return AvailableMediaTypeCompositionResponseModelToJSONTyped(json, false);
}

export function AvailableMediaTypeCompositionResponseModelToJSONTyped(value?: AvailableMediaTypeCompositionResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'icon': value['icon'],
        'folderPath': value['folderPath'],
        'isCompatible': value['isCompatible'],
    };
}

