/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserDataRequestModel
 */
export interface CreateUserDataRequestModel {
    /**
     * 
     * @type {string}
     * @memberof CreateUserDataRequestModel
     */
    group: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDataRequestModel
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDataRequestModel
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDataRequestModel
     */
    key?: string | null;
}

/**
 * Check if a given object implements the CreateUserDataRequestModel interface.
 */
export function instanceOfCreateUserDataRequestModel(value: object): value is CreateUserDataRequestModel {
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CreateUserDataRequestModelFromJSON(json: any): CreateUserDataRequestModel {
    return CreateUserDataRequestModelFromJSONTyped(json, false);
}

export function CreateUserDataRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDataRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'group': json['group'],
        'identifier': json['identifier'],
        'value': json['value'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function CreateUserDataRequestModelToJSON(json: any): CreateUserDataRequestModel {
    return CreateUserDataRequestModelToJSONTyped(json, false);
}

export function CreateUserDataRequestModelToJSONTyped(value?: CreateUserDataRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': value['group'],
        'identifier': value['identifier'],
        'value': value['value'],
        'key': value['key'],
    };
}

