/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileSystemFolderModel } from './FileSystemFolderModel';
import {
    FileSystemFolderModelFromJSON,
    FileSystemFolderModelFromJSONTyped,
    FileSystemFolderModelToJSON,
    FileSystemFolderModelToJSONTyped,
} from './FileSystemFolderModel';

/**
 * 
 * @export
 * @interface CreateScriptRequestModel
 */
export interface CreateScriptRequestModel {
    /**
     * 
     * @type {string}
     * @memberof CreateScriptRequestModel
     */
    name: string;
    /**
     * 
     * @type {FileSystemFolderModel}
     * @memberof CreateScriptRequestModel
     */
    parent?: FileSystemFolderModel | null;
    /**
     * 
     * @type {string}
     * @memberof CreateScriptRequestModel
     */
    content: string;
}

/**
 * Check if a given object implements the CreateScriptRequestModel interface.
 */
export function instanceOfCreateScriptRequestModel(value: object): value is CreateScriptRequestModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateScriptRequestModelFromJSON(json: any): CreateScriptRequestModel {
    return CreateScriptRequestModelFromJSONTyped(json, false);
}

export function CreateScriptRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateScriptRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'parent': json['parent'] == null ? undefined : FileSystemFolderModelFromJSON(json['parent']),
        'content': json['content'],
    };
}

export function CreateScriptRequestModelToJSON(json: any): CreateScriptRequestModel {
    return CreateScriptRequestModelToJSONTyped(json, false);
}

export function CreateScriptRequestModelToJSONTyped(value?: CreateScriptRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'parent': FileSystemFolderModelToJSON(value['parent']),
        'content': value['content'],
    };
}

