/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateMemberTypeRequestModelContainersInner } from './CreateMemberTypeRequestModelContainersInner';
import {
    CreateMemberTypeRequestModelContainersInnerFromJSON,
    CreateMemberTypeRequestModelContainersInnerFromJSONTyped,
    CreateMemberTypeRequestModelContainersInnerToJSON,
    CreateMemberTypeRequestModelContainersInnerToJSONTyped,
} from './CreateMemberTypeRequestModelContainersInner';
import type { CreateMemberTypeRequestModelPropertiesInner } from './CreateMemberTypeRequestModelPropertiesInner';
import {
    CreateMemberTypeRequestModelPropertiesInnerFromJSON,
    CreateMemberTypeRequestModelPropertiesInnerFromJSONTyped,
    CreateMemberTypeRequestModelPropertiesInnerToJSON,
    CreateMemberTypeRequestModelPropertiesInnerToJSONTyped,
} from './CreateMemberTypeRequestModelPropertiesInner';
import type { CreateMemberTypeRequestModelCompositionsInner } from './CreateMemberTypeRequestModelCompositionsInner';
import {
    CreateMemberTypeRequestModelCompositionsInnerFromJSON,
    CreateMemberTypeRequestModelCompositionsInnerFromJSONTyped,
    CreateMemberTypeRequestModelCompositionsInnerToJSON,
    CreateMemberTypeRequestModelCompositionsInnerToJSONTyped,
} from './CreateMemberTypeRequestModelCompositionsInner';
import type { ReferenceByIdModel } from './ReferenceByIdModel';
import {
    ReferenceByIdModelFromJSON,
    ReferenceByIdModelFromJSONTyped,
    ReferenceByIdModelToJSON,
    ReferenceByIdModelToJSONTyped,
} from './ReferenceByIdModel';

/**
 * 
 * @export
 * @interface CreateMemberTypeRequestModel
 */
export interface CreateMemberTypeRequestModel {
    /**
     * 
     * @type {string}
     * @memberof CreateMemberTypeRequestModel
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMemberTypeRequestModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMemberTypeRequestModel
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMemberTypeRequestModel
     */
    icon: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateMemberTypeRequestModel
     */
    allowedAsRoot: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateMemberTypeRequestModel
     */
    variesByCulture: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateMemberTypeRequestModel
     */
    variesBySegment: boolean;
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof CreateMemberTypeRequestModel
     */
    collection?: ReferenceByIdModel | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateMemberTypeRequestModel
     */
    isElement: boolean;
    /**
     * 
     * @type {Array<CreateMemberTypeRequestModelPropertiesInner>}
     * @memberof CreateMemberTypeRequestModel
     */
    properties: Array<CreateMemberTypeRequestModelPropertiesInner>;
    /**
     * 
     * @type {Array<CreateMemberTypeRequestModelContainersInner>}
     * @memberof CreateMemberTypeRequestModel
     */
    containers: Array<CreateMemberTypeRequestModelContainersInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateMemberTypeRequestModel
     */
    id?: string | null;
    /**
     * 
     * @type {Array<CreateMemberTypeRequestModelCompositionsInner>}
     * @memberof CreateMemberTypeRequestModel
     */
    compositions: Array<CreateMemberTypeRequestModelCompositionsInner>;
}

/**
 * Check if a given object implements the CreateMemberTypeRequestModel interface.
 */
export function instanceOfCreateMemberTypeRequestModel(value: object): value is CreateMemberTypeRequestModel {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('allowedAsRoot' in value) || value['allowedAsRoot'] === undefined) return false;
    if (!('variesByCulture' in value) || value['variesByCulture'] === undefined) return false;
    if (!('variesBySegment' in value) || value['variesBySegment'] === undefined) return false;
    if (!('isElement' in value) || value['isElement'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    if (!('containers' in value) || value['containers'] === undefined) return false;
    if (!('compositions' in value) || value['compositions'] === undefined) return false;
    return true;
}

export function CreateMemberTypeRequestModelFromJSON(json: any): CreateMemberTypeRequestModel {
    return CreateMemberTypeRequestModelFromJSONTyped(json, false);
}

export function CreateMemberTypeRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMemberTypeRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'],
        'allowedAsRoot': json['allowedAsRoot'],
        'variesByCulture': json['variesByCulture'],
        'variesBySegment': json['variesBySegment'],
        'collection': json['collection'] == null ? undefined : ReferenceByIdModelFromJSON(json['collection']),
        'isElement': json['isElement'],
        'properties': ((json['properties'] as Array<any>).map(CreateMemberTypeRequestModelPropertiesInnerFromJSON)),
        'containers': ((json['containers'] as Array<any>).map(CreateMemberTypeRequestModelContainersInnerFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'compositions': ((json['compositions'] as Array<any>).map(CreateMemberTypeRequestModelCompositionsInnerFromJSON)),
    };
}

export function CreateMemberTypeRequestModelToJSON(json: any): CreateMemberTypeRequestModel {
    return CreateMemberTypeRequestModelToJSONTyped(json, false);
}

export function CreateMemberTypeRequestModelToJSONTyped(value?: CreateMemberTypeRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'allowedAsRoot': value['allowedAsRoot'],
        'variesByCulture': value['variesByCulture'],
        'variesBySegment': value['variesBySegment'],
        'collection': ReferenceByIdModelToJSON(value['collection']),
        'isElement': value['isElement'],
        'properties': ((value['properties'] as Array<any>).map(CreateMemberTypeRequestModelPropertiesInnerToJSON)),
        'containers': ((value['containers'] as Array<any>).map(CreateMemberTypeRequestModelContainersInnerToJSON)),
        'id': value['id'],
        'compositions': ((value['compositions'] as Array<any>).map(CreateMemberTypeRequestModelCompositionsInnerToJSON)),
    };
}

