/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CultureReponseModel
 */
export interface CultureReponseModel {
    /**
     * 
     * @type {string}
     * @memberof CultureReponseModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CultureReponseModel
     */
    englishName: string;
}

/**
 * Check if a given object implements the CultureReponseModel interface.
 */
export function instanceOfCultureReponseModel(value: object): value is CultureReponseModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('englishName' in value) || value['englishName'] === undefined) return false;
    return true;
}

export function CultureReponseModelFromJSON(json: any): CultureReponseModel {
    return CultureReponseModelFromJSONTyped(json, false);
}

export function CultureReponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CultureReponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'englishName': json['englishName'],
    };
}

export function CultureReponseModelToJSON(json: any): CultureReponseModel {
    return CultureReponseModelToJSONTyped(json, false);
}

export function CultureReponseModelToJSONTyped(value?: CultureReponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'englishName': value['englishName'],
    };
}

