/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PasswordConfigurationResponseModel } from './PasswordConfigurationResponseModel';
import {
    PasswordConfigurationResponseModelFromJSON,
    PasswordConfigurationResponseModelFromJSONTyped,
    PasswordConfigurationResponseModelToJSON,
    PasswordConfigurationResponseModelToJSONTyped,
} from './PasswordConfigurationResponseModel';

/**
 * 
 * @export
 * @interface CurrentUserConfigurationResponseModel
 */
export interface CurrentUserConfigurationResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof CurrentUserConfigurationResponseModel
     */
    keepUserLoggedIn: boolean;
    /**
     * 
     * @type {PasswordConfigurationResponseModel}
     * @memberof CurrentUserConfigurationResponseModel
     */
    passwordConfiguration: PasswordConfigurationResponseModel;
    /**
     * 
     * @type {boolean}
     * @memberof CurrentUserConfigurationResponseModel
     */
    allowChangePassword: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CurrentUserConfigurationResponseModel
     */
    allowTwoFactor: boolean;
}

/**
 * Check if a given object implements the CurrentUserConfigurationResponseModel interface.
 */
export function instanceOfCurrentUserConfigurationResponseModel(value: object): value is CurrentUserConfigurationResponseModel {
    if (!('keepUserLoggedIn' in value) || value['keepUserLoggedIn'] === undefined) return false;
    if (!('passwordConfiguration' in value) || value['passwordConfiguration'] === undefined) return false;
    if (!('allowChangePassword' in value) || value['allowChangePassword'] === undefined) return false;
    if (!('allowTwoFactor' in value) || value['allowTwoFactor'] === undefined) return false;
    return true;
}

export function CurrentUserConfigurationResponseModelFromJSON(json: any): CurrentUserConfigurationResponseModel {
    return CurrentUserConfigurationResponseModelFromJSONTyped(json, false);
}

export function CurrentUserConfigurationResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserConfigurationResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'keepUserLoggedIn': json['keepUserLoggedIn'],
        'passwordConfiguration': PasswordConfigurationResponseModelFromJSON(json['passwordConfiguration']),
        'allowChangePassword': json['allowChangePassword'],
        'allowTwoFactor': json['allowTwoFactor'],
    };
}

export function CurrentUserConfigurationResponseModelToJSON(json: any): CurrentUserConfigurationResponseModel {
    return CurrentUserConfigurationResponseModelToJSONTyped(json, false);
}

export function CurrentUserConfigurationResponseModelToJSONTyped(value?: CurrentUserConfigurationResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keepUserLoggedIn': value['keepUserLoggedIn'],
        'passwordConfiguration': PasswordConfigurationResponseModelToJSON(value['passwordConfiguration']),
        'allowChangePassword': value['allowChangePassword'],
        'allowTwoFactor': value['allowTwoFactor'],
    };
}

