/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DictionaryItemItemResponseModel
 */
export interface DictionaryItemItemResponseModel {
    /**
     * 
     * @type {string}
     * @memberof DictionaryItemItemResponseModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DictionaryItemItemResponseModel
     */
    name: string;
}

/**
 * Check if a given object implements the DictionaryItemItemResponseModel interface.
 */
export function instanceOfDictionaryItemItemResponseModel(value: object): value is DictionaryItemItemResponseModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DictionaryItemItemResponseModelFromJSON(json: any): DictionaryItemItemResponseModel {
    return DictionaryItemItemResponseModelFromJSONTyped(json, false);
}

export function DictionaryItemItemResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DictionaryItemItemResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function DictionaryItemItemResponseModelToJSON(json: any): DictionaryItemItemResponseModel {
    return DictionaryItemItemResponseModelToJSONTyped(json, false);
}

export function DictionaryItemItemResponseModelToJSONTyped(value?: DictionaryItemItemResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

