/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DocumentVariantResponseModel } from './DocumentVariantResponseModel';
import {
    instanceOfDocumentVariantResponseModel,
    DocumentVariantResponseModelFromJSON,
    DocumentVariantResponseModelFromJSONTyped,
    DocumentVariantResponseModelToJSON,
} from './DocumentVariantResponseModel';

/**
 * @type DocumentBlueprintResponseModelVariantsInner
 * 
 * @export
 */
export type DocumentBlueprintResponseModelVariantsInner = DocumentVariantResponseModel;

export function DocumentBlueprintResponseModelVariantsInnerFromJSON(json: any): DocumentBlueprintResponseModelVariantsInner {
    return DocumentBlueprintResponseModelVariantsInnerFromJSONTyped(json, false);
}

export function DocumentBlueprintResponseModelVariantsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentBlueprintResponseModelVariantsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDocumentVariantResponseModel(json)) {
        return DocumentVariantResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function DocumentBlueprintResponseModelVariantsInnerToJSON(json: any): any {
    return DocumentBlueprintResponseModelVariantsInnerToJSONTyped(json, false);
}

export function DocumentBlueprintResponseModelVariantsInnerToJSONTyped(value?: DocumentBlueprintResponseModelVariantsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDocumentVariantResponseModel(value)) {
        return DocumentVariantResponseModelToJSON(value as DocumentVariantResponseModel);
    }

    return {};
}

