/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentBlueprintResponseModelVariantsInner } from './DocumentBlueprintResponseModelVariantsInner';
import {
    DocumentBlueprintResponseModelVariantsInnerFromJSON,
    DocumentBlueprintResponseModelVariantsInnerFromJSONTyped,
    DocumentBlueprintResponseModelVariantsInnerToJSON,
    DocumentBlueprintResponseModelVariantsInnerToJSONTyped,
} from './DocumentBlueprintResponseModelVariantsInner';
import type { PostUserGroupByIdUsersRequestInner } from './PostUserGroupByIdUsersRequestInner';
import {
    PostUserGroupByIdUsersRequestInnerFromJSON,
    PostUserGroupByIdUsersRequestInnerFromJSONTyped,
    PostUserGroupByIdUsersRequestInnerToJSON,
    PostUserGroupByIdUsersRequestInnerToJSONTyped,
} from './PostUserGroupByIdUsersRequestInner';
import type { DocumentBlueprintResponseModelValuesInner } from './DocumentBlueprintResponseModelValuesInner';
import {
    DocumentBlueprintResponseModelValuesInnerFromJSON,
    DocumentBlueprintResponseModelValuesInnerFromJSONTyped,
    DocumentBlueprintResponseModelValuesInnerToJSON,
    DocumentBlueprintResponseModelValuesInnerToJSONTyped,
} from './DocumentBlueprintResponseModelValuesInner';
import type { DocumentTypeCollectionReferenceResponseModel } from './DocumentTypeCollectionReferenceResponseModel';
import {
    DocumentTypeCollectionReferenceResponseModelFromJSON,
    DocumentTypeCollectionReferenceResponseModelFromJSONTyped,
    DocumentTypeCollectionReferenceResponseModelToJSON,
    DocumentTypeCollectionReferenceResponseModelToJSONTyped,
} from './DocumentTypeCollectionReferenceResponseModel';

/**
 * 
 * @export
 * @interface DocumentCollectionResponseModel
 */
export interface DocumentCollectionResponseModel {
    /**
     * 
     * @type {Array<DocumentBlueprintResponseModelValuesInner>}
     * @memberof DocumentCollectionResponseModel
     */
    values: Array<DocumentBlueprintResponseModelValuesInner>;
    /**
     * 
     * @type {Array<DocumentBlueprintResponseModelVariantsInner>}
     * @memberof DocumentCollectionResponseModel
     */
    variants: Array<DocumentBlueprintResponseModelVariantsInner>;
    /**
     * 
     * @type {string}
     * @memberof DocumentCollectionResponseModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCollectionResponseModel
     */
    creator?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentCollectionResponseModel
     */
    sortOrder: number;
    /**
     * 
     * @type {DocumentTypeCollectionReferenceResponseModel}
     * @memberof DocumentCollectionResponseModel
     */
    documentType: DocumentTypeCollectionReferenceResponseModel;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentCollectionResponseModel
     */
    isTrashed: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentCollectionResponseModel
     */
    isProtected: boolean;
    /**
     * 
     * @type {Array<PostUserGroupByIdUsersRequestInner>}
     * @memberof DocumentCollectionResponseModel
     */
    ancestors: Array<PostUserGroupByIdUsersRequestInner>;
    /**
     * 
     * @type {string}
     * @memberof DocumentCollectionResponseModel
     */
    updater?: string | null;
}

/**
 * Check if a given object implements the DocumentCollectionResponseModel interface.
 */
export function instanceOfDocumentCollectionResponseModel(value: object): value is DocumentCollectionResponseModel {
    if (!('values' in value) || value['values'] === undefined) return false;
    if (!('variants' in value) || value['variants'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('documentType' in value) || value['documentType'] === undefined) return false;
    if (!('isTrashed' in value) || value['isTrashed'] === undefined) return false;
    if (!('isProtected' in value) || value['isProtected'] === undefined) return false;
    if (!('ancestors' in value) || value['ancestors'] === undefined) return false;
    return true;
}

export function DocumentCollectionResponseModelFromJSON(json: any): DocumentCollectionResponseModel {
    return DocumentCollectionResponseModelFromJSONTyped(json, false);
}

export function DocumentCollectionResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCollectionResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'values': ((json['values'] as Array<any>).map(DocumentBlueprintResponseModelValuesInnerFromJSON)),
        'variants': ((json['variants'] as Array<any>).map(DocumentBlueprintResponseModelVariantsInnerFromJSON)),
        'id': json['id'],
        'creator': json['creator'] == null ? undefined : json['creator'],
        'sortOrder': json['sortOrder'],
        'documentType': DocumentTypeCollectionReferenceResponseModelFromJSON(json['documentType']),
        'isTrashed': json['isTrashed'],
        'isProtected': json['isProtected'],
        'ancestors': ((json['ancestors'] as Array<any>).map(PostUserGroupByIdUsersRequestInnerFromJSON)),
        'updater': json['updater'] == null ? undefined : json['updater'],
    };
}

export function DocumentCollectionResponseModelToJSON(json: any): DocumentCollectionResponseModel {
    return DocumentCollectionResponseModelToJSONTyped(json, false);
}

export function DocumentCollectionResponseModelToJSONTyped(value?: DocumentCollectionResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': ((value['values'] as Array<any>).map(DocumentBlueprintResponseModelValuesInnerToJSON)),
        'variants': ((value['variants'] as Array<any>).map(DocumentBlueprintResponseModelVariantsInnerToJSON)),
        'id': value['id'],
        'creator': value['creator'],
        'sortOrder': value['sortOrder'],
        'documentType': DocumentTypeCollectionReferenceResponseModelToJSON(value['documentType']),
        'isTrashed': value['isTrashed'],
        'isProtected': value['isProtected'],
        'ancestors': ((value['ancestors'] as Array<any>).map(PostUserGroupByIdUsersRequestInnerToJSON)),
        'updater': value['updater'],
    };
}

