/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentVariantRequestModel
 */
export interface DocumentVariantRequestModel {
    /**
     * 
     * @type {string}
     * @memberof DocumentVariantRequestModel
     */
    culture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVariantRequestModel
     */
    segment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVariantRequestModel
     */
    name: string;
}

/**
 * Check if a given object implements the DocumentVariantRequestModel interface.
 */
export function instanceOfDocumentVariantRequestModel(value: object): value is DocumentVariantRequestModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DocumentVariantRequestModelFromJSON(json: any): DocumentVariantRequestModel {
    return DocumentVariantRequestModelFromJSONTyped(json, false);
}

export function DocumentVariantRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentVariantRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'culture': json['culture'] == null ? undefined : json['culture'],
        'segment': json['segment'] == null ? undefined : json['segment'],
        'name': json['name'],
    };
}

export function DocumentVariantRequestModelToJSON(json: any): DocumentVariantRequestModel {
    return DocumentVariantRequestModelToJSONTyped(json, false);
}

export function DocumentVariantRequestModelToJSONTyped(value?: DocumentVariantRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'culture': value['culture'],
        'segment': value['segment'],
        'name': value['name'],
    };
}

