/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostUserGroupByIdUsersRequestInner } from './PostUserGroupByIdUsersRequestInner';
import {
    PostUserGroupByIdUsersRequestInnerFromJSON,
    PostUserGroupByIdUsersRequestInnerFromJSONTyped,
    PostUserGroupByIdUsersRequestInnerToJSON,
    PostUserGroupByIdUsersRequestInnerToJSONTyped,
} from './PostUserGroupByIdUsersRequestInner';
import type { DocumentTypeReferenceResponseModel } from './DocumentTypeReferenceResponseModel';
import {
    DocumentTypeReferenceResponseModelFromJSON,
    DocumentTypeReferenceResponseModelFromJSONTyped,
    DocumentTypeReferenceResponseModelToJSON,
    DocumentTypeReferenceResponseModelToJSONTyped,
} from './DocumentTypeReferenceResponseModel';
import type { DocumentItemResponseModelVariantsInner } from './DocumentItemResponseModelVariantsInner';
import {
    DocumentItemResponseModelVariantsInnerFromJSON,
    DocumentItemResponseModelVariantsInnerFromJSONTyped,
    DocumentItemResponseModelVariantsInnerToJSON,
    DocumentItemResponseModelVariantsInnerToJSONTyped,
} from './DocumentItemResponseModelVariantsInner';
import type { ReferenceByIdModel } from './ReferenceByIdModel';
import {
    ReferenceByIdModelFromJSON,
    ReferenceByIdModelFromJSONTyped,
    ReferenceByIdModelToJSON,
    ReferenceByIdModelToJSONTyped,
} from './ReferenceByIdModel';

/**
 * 
 * @export
 * @interface DocumentTreeItemResponseModel
 */
export interface DocumentTreeItemResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof DocumentTreeItemResponseModel
     */
    hasChildren: boolean;
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof DocumentTreeItemResponseModel
     */
    parent?: ReferenceByIdModel | null;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentTreeItemResponseModel
     */
    noAccess: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentTreeItemResponseModel
     */
    isTrashed: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentTreeItemResponseModel
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof DocumentTreeItemResponseModel
     */
    createDate: Date;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentTreeItemResponseModel
     */
    isProtected: boolean;
    /**
     * 
     * @type {Array<PostUserGroupByIdUsersRequestInner>}
     * @memberof DocumentTreeItemResponseModel
     */
    ancestors: Array<PostUserGroupByIdUsersRequestInner>;
    /**
     * 
     * @type {DocumentTypeReferenceResponseModel}
     * @memberof DocumentTreeItemResponseModel
     */
    documentType: DocumentTypeReferenceResponseModel;
    /**
     * 
     * @type {Array<DocumentItemResponseModelVariantsInner>}
     * @memberof DocumentTreeItemResponseModel
     */
    variants: Array<DocumentItemResponseModelVariantsInner>;
}

/**
 * Check if a given object implements the DocumentTreeItemResponseModel interface.
 */
export function instanceOfDocumentTreeItemResponseModel(value: object): value is DocumentTreeItemResponseModel {
    if (!('hasChildren' in value) || value['hasChildren'] === undefined) return false;
    if (!('noAccess' in value) || value['noAccess'] === undefined) return false;
    if (!('isTrashed' in value) || value['isTrashed'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createDate' in value) || value['createDate'] === undefined) return false;
    if (!('isProtected' in value) || value['isProtected'] === undefined) return false;
    if (!('ancestors' in value) || value['ancestors'] === undefined) return false;
    if (!('documentType' in value) || value['documentType'] === undefined) return false;
    if (!('variants' in value) || value['variants'] === undefined) return false;
    return true;
}

export function DocumentTreeItemResponseModelFromJSON(json: any): DocumentTreeItemResponseModel {
    return DocumentTreeItemResponseModelFromJSONTyped(json, false);
}

export function DocumentTreeItemResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentTreeItemResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'hasChildren': json['hasChildren'],
        'parent': json['parent'] == null ? undefined : ReferenceByIdModelFromJSON(json['parent']),
        'noAccess': json['noAccess'],
        'isTrashed': json['isTrashed'],
        'id': json['id'],
        'createDate': (new Date(json['createDate'])),
        'isProtected': json['isProtected'],
        'ancestors': ((json['ancestors'] as Array<any>).map(PostUserGroupByIdUsersRequestInnerFromJSON)),
        'documentType': DocumentTypeReferenceResponseModelFromJSON(json['documentType']),
        'variants': ((json['variants'] as Array<any>).map(DocumentItemResponseModelVariantsInnerFromJSON)),
    };
}

export function DocumentTreeItemResponseModelToJSON(json: any): DocumentTreeItemResponseModel {
    return DocumentTreeItemResponseModelToJSONTyped(json, false);
}

export function DocumentTreeItemResponseModelToJSONTyped(value?: DocumentTreeItemResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasChildren': value['hasChildren'],
        'parent': ReferenceByIdModelToJSON(value['parent']),
        'noAccess': value['noAccess'],
        'isTrashed': value['isTrashed'],
        'id': value['id'],
        'createDate': ((value['createDate']).toISOString()),
        'isProtected': value['isProtected'],
        'ancestors': ((value['ancestors'] as Array<any>).map(PostUserGroupByIdUsersRequestInnerToJSON)),
        'documentType': DocumentTypeReferenceResponseModelToJSON(value['documentType']),
        'variants': ((value['variants'] as Array<any>).map(DocumentItemResponseModelVariantsInnerToJSON)),
    };
}

