/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentBlueprintResponseModelVariantsInner } from './DocumentBlueprintResponseModelVariantsInner';
import {
    DocumentBlueprintResponseModelVariantsInnerFromJSON,
    DocumentBlueprintResponseModelVariantsInnerFromJSONTyped,
    DocumentBlueprintResponseModelVariantsInnerToJSON,
    DocumentBlueprintResponseModelVariantsInnerToJSONTyped,
} from './DocumentBlueprintResponseModelVariantsInner';
import type { DocumentTypeReferenceResponseModel } from './DocumentTypeReferenceResponseModel';
import {
    DocumentTypeReferenceResponseModelFromJSON,
    DocumentTypeReferenceResponseModelFromJSONTyped,
    DocumentTypeReferenceResponseModelToJSON,
    DocumentTypeReferenceResponseModelToJSONTyped,
} from './DocumentTypeReferenceResponseModel';
import type { DocumentBlueprintResponseModelValuesInner } from './DocumentBlueprintResponseModelValuesInner';
import {
    DocumentBlueprintResponseModelValuesInnerFromJSON,
    DocumentBlueprintResponseModelValuesInnerFromJSONTyped,
    DocumentBlueprintResponseModelValuesInnerToJSON,
    DocumentBlueprintResponseModelValuesInnerToJSONTyped,
} from './DocumentBlueprintResponseModelValuesInner';

/**
 * 
 * @export
 * @interface DocumentBlueprintResponseModel
 */
export interface DocumentBlueprintResponseModel {
    /**
     * 
     * @type {Array<DocumentBlueprintResponseModelValuesInner>}
     * @memberof DocumentBlueprintResponseModel
     */
    values: Array<DocumentBlueprintResponseModelValuesInner>;
    /**
     * 
     * @type {Array<DocumentBlueprintResponseModelVariantsInner>}
     * @memberof DocumentBlueprintResponseModel
     */
    variants: Array<DocumentBlueprintResponseModelVariantsInner>;
    /**
     * 
     * @type {string}
     * @memberof DocumentBlueprintResponseModel
     */
    id: string;
    /**
     * 
     * @type {DocumentTypeReferenceResponseModel}
     * @memberof DocumentBlueprintResponseModel
     */
    documentType: DocumentTypeReferenceResponseModel;
}

/**
 * Check if a given object implements the DocumentBlueprintResponseModel interface.
 */
export function instanceOfDocumentBlueprintResponseModel(value: object): value is DocumentBlueprintResponseModel {
    if (!('values' in value) || value['values'] === undefined) return false;
    if (!('variants' in value) || value['variants'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('documentType' in value) || value['documentType'] === undefined) return false;
    return true;
}

export function DocumentBlueprintResponseModelFromJSON(json: any): DocumentBlueprintResponseModel {
    return DocumentBlueprintResponseModelFromJSONTyped(json, false);
}

export function DocumentBlueprintResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentBlueprintResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'values': ((json['values'] as Array<any>).map(DocumentBlueprintResponseModelValuesInnerFromJSON)),
        'variants': ((json['variants'] as Array<any>).map(DocumentBlueprintResponseModelVariantsInnerFromJSON)),
        'id': json['id'],
        'documentType': DocumentTypeReferenceResponseModelFromJSON(json['documentType']),
    };
}

export function DocumentBlueprintResponseModelToJSON(json: any): DocumentBlueprintResponseModel {
    return DocumentBlueprintResponseModelToJSONTyped(json, false);
}

export function DocumentBlueprintResponseModelToJSONTyped(value?: DocumentBlueprintResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': ((value['values'] as Array<any>).map(DocumentBlueprintResponseModelValuesInnerToJSON)),
        'variants': ((value['variants'] as Array<any>).map(DocumentBlueprintResponseModelVariantsInnerToJSON)),
        'id': value['id'],
        'documentType': DocumentTypeReferenceResponseModelToJSON(value['documentType']),
    };
}

