/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnableTwoFactorRequestModel
 */
export interface EnableTwoFactorRequestModel {
    /**
     * 
     * @type {string}
     * @memberof EnableTwoFactorRequestModel
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof EnableTwoFactorRequestModel
     */
    secret: string;
}

/**
 * Check if a given object implements the EnableTwoFactorRequestModel interface.
 */
export function instanceOfEnableTwoFactorRequestModel(value: object): value is EnableTwoFactorRequestModel {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function EnableTwoFactorRequestModelFromJSON(json: any): EnableTwoFactorRequestModel {
    return EnableTwoFactorRequestModelFromJSONTyped(json, false);
}

export function EnableTwoFactorRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnableTwoFactorRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'secret': json['secret'],
    };
}

export function EnableTwoFactorRequestModelToJSON(json: any): EnableTwoFactorRequestModel {
    return EnableTwoFactorRequestModelToJSONTyped(json, false);
}

export function EnableTwoFactorRequestModelToJSONTyped(value?: EnableTwoFactorRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'secret': value['secret'],
    };
}

