/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LanguageItemResponseModel } from './LanguageItemResponseModel';
import {
    instanceOfLanguageItemResponseModel,
    LanguageItemResponseModelFromJSON,
    LanguageItemResponseModelFromJSONTyped,
    LanguageItemResponseModelToJSON,
} from './LanguageItemResponseModel';

/**
 * @type GetItemLanguage200ResponseInner
 * 
 * @export
 */
export type GetItemLanguage200ResponseInner = LanguageItemResponseModel;

export function GetItemLanguage200ResponseInnerFromJSON(json: any): GetItemLanguage200ResponseInner {
    return GetItemLanguage200ResponseInnerFromJSONTyped(json, false);
}

export function GetItemLanguage200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetItemLanguage200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfLanguageItemResponseModel(json)) {
        return LanguageItemResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetItemLanguage200ResponseInnerToJSON(json: any): any {
    return GetItemLanguage200ResponseInnerToJSONTyped(json, false);
}

export function GetItemLanguage200ResponseInnerToJSONTyped(value?: GetItemLanguage200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfLanguageItemResponseModel(value)) {
        return LanguageItemResponseModelToJSON(value as LanguageItemResponseModel);
    }

    return {};
}

