/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TemplateItemResponseModel } from './TemplateItemResponseModel';
import {
    instanceOfTemplateItemResponseModel,
    TemplateItemResponseModelFromJSON,
    TemplateItemResponseModelFromJSONTyped,
    TemplateItemResponseModelToJSON,
} from './TemplateItemResponseModel';

/**
 * @type GetItemTemplate200ResponseInner
 * 
 * @export
 */
export type GetItemTemplate200ResponseInner = TemplateItemResponseModel;

export function GetItemTemplate200ResponseInnerFromJSON(json: any): GetItemTemplate200ResponseInner {
    return GetItemTemplate200ResponseInnerFromJSONTyped(json, false);
}

export function GetItemTemplate200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetItemTemplate200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfTemplateItemResponseModel(json)) {
        return TemplateItemResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetItemTemplate200ResponseInnerToJSON(json: any): any {
    return GetItemTemplate200ResponseInnerToJSONTyped(json, false);
}

export function GetItemTemplate200ResponseInnerToJSONTyped(value?: GetItemTemplate200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfTemplateItemResponseModel(value)) {
        return TemplateItemResponseModelToJSON(value as TemplateItemResponseModel);
    }

    return {};
}

