/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MediaTypeCompositionResponseModel } from './MediaTypeCompositionResponseModel';
import {
    instanceOfMediaTypeCompositionResponseModel,
    MediaTypeCompositionResponseModelFromJSON,
    MediaTypeCompositionResponseModelFromJSONTyped,
    MediaTypeCompositionResponseModelToJSON,
} from './MediaTypeCompositionResponseModel';

/**
 * @type GetMediaTypeByIdCompositionReferences200ResponseInner
 * 
 * @export
 */
export type GetMediaTypeByIdCompositionReferences200ResponseInner = MediaTypeCompositionResponseModel;

export function GetMediaTypeByIdCompositionReferences200ResponseInnerFromJSON(json: any): GetMediaTypeByIdCompositionReferences200ResponseInner {
    return GetMediaTypeByIdCompositionReferences200ResponseInnerFromJSONTyped(json, false);
}

export function GetMediaTypeByIdCompositionReferences200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMediaTypeByIdCompositionReferences200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfMediaTypeCompositionResponseModel(json)) {
        return MediaTypeCompositionResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetMediaTypeByIdCompositionReferences200ResponseInnerToJSON(json: any): any {
    return GetMediaTypeByIdCompositionReferences200ResponseInnerToJSONTyped(json, false);
}

export function GetMediaTypeByIdCompositionReferences200ResponseInnerToJSONTyped(value?: GetMediaTypeByIdCompositionReferences200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfMediaTypeCompositionResponseModel(value)) {
        return MediaTypeCompositionResponseModelToJSON(value as MediaTypeCompositionResponseModel);
    }

    return {};
}

