/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DocumentBlueprintTreeItemResponseModel } from './DocumentBlueprintTreeItemResponseModel';
import {
    instanceOfDocumentBlueprintTreeItemResponseModel,
    DocumentBlueprintTreeItemResponseModelFromJSON,
    DocumentBlueprintTreeItemResponseModelFromJSONTyped,
    DocumentBlueprintTreeItemResponseModelToJSON,
} from './DocumentBlueprintTreeItemResponseModel';

/**
 * @type GetTreeDocumentBlueprintAncestors200ResponseInner
 * 
 * @export
 */
export type GetTreeDocumentBlueprintAncestors200ResponseInner = DocumentBlueprintTreeItemResponseModel;

export function GetTreeDocumentBlueprintAncestors200ResponseInnerFromJSON(json: any): GetTreeDocumentBlueprintAncestors200ResponseInner {
    return GetTreeDocumentBlueprintAncestors200ResponseInnerFromJSONTyped(json, false);
}

export function GetTreeDocumentBlueprintAncestors200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTreeDocumentBlueprintAncestors200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDocumentBlueprintTreeItemResponseModel(json)) {
        return DocumentBlueprintTreeItemResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetTreeDocumentBlueprintAncestors200ResponseInnerToJSON(json: any): any {
    return GetTreeDocumentBlueprintAncestors200ResponseInnerToJSONTyped(json, false);
}

export function GetTreeDocumentBlueprintAncestors200ResponseInnerToJSONTyped(value?: GetTreeDocumentBlueprintAncestors200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDocumentBlueprintTreeItemResponseModel(value)) {
        return DocumentBlueprintTreeItemResponseModelToJSON(value as DocumentBlueprintTreeItemResponseModel);
    }

    return {};
}

