/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DocumentTypeTreeItemResponseModel } from './DocumentTypeTreeItemResponseModel';
import {
    instanceOfDocumentTypeTreeItemResponseModel,
    DocumentTypeTreeItemResponseModelFromJSON,
    DocumentTypeTreeItemResponseModelFromJSONTyped,
    DocumentTypeTreeItemResponseModelToJSON,
} from './DocumentTypeTreeItemResponseModel';

/**
 * @type GetTreeDocumentTypeAncestors200ResponseInner
 * 
 * @export
 */
export type GetTreeDocumentTypeAncestors200ResponseInner = DocumentTypeTreeItemResponseModel;

export function GetTreeDocumentTypeAncestors200ResponseInnerFromJSON(json: any): GetTreeDocumentTypeAncestors200ResponseInner {
    return GetTreeDocumentTypeAncestors200ResponseInnerFromJSONTyped(json, false);
}

export function GetTreeDocumentTypeAncestors200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTreeDocumentTypeAncestors200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDocumentTypeTreeItemResponseModel(json)) {
        return DocumentTypeTreeItemResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetTreeDocumentTypeAncestors200ResponseInnerToJSON(json: any): any {
    return GetTreeDocumentTypeAncestors200ResponseInnerToJSONTyped(json, false);
}

export function GetTreeDocumentTypeAncestors200ResponseInnerToJSONTyped(value?: GetTreeDocumentTypeAncestors200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDocumentTypeTreeItemResponseModel(value)) {
        return DocumentTypeTreeItemResponseModelToJSON(value as DocumentTypeTreeItemResponseModel);
    }

    return {};
}

