/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DocumentTreeItemResponseModel } from './DocumentTreeItemResponseModel';
import {
    instanceOfDocumentTreeItemResponseModel,
    DocumentTreeItemResponseModelFromJSON,
    DocumentTreeItemResponseModelFromJSONTyped,
    DocumentTreeItemResponseModelToJSON,
} from './DocumentTreeItemResponseModel';

/**
 * @type GetTreeDocumentAncestors200ResponseInner
 * 
 * @export
 */
export type GetTreeDocumentAncestors200ResponseInner = DocumentTreeItemResponseModel;

export function GetTreeDocumentAncestors200ResponseInnerFromJSON(json: any): GetTreeDocumentAncestors200ResponseInner {
    return GetTreeDocumentAncestors200ResponseInnerFromJSONTyped(json, false);
}

export function GetTreeDocumentAncestors200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTreeDocumentAncestors200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDocumentTreeItemResponseModel(json)) {
        return DocumentTreeItemResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetTreeDocumentAncestors200ResponseInnerToJSON(json: any): any {
    return GetTreeDocumentAncestors200ResponseInnerToJSONTyped(json, false);
}

export function GetTreeDocumentAncestors200ResponseInnerToJSONTyped(value?: GetTreeDocumentAncestors200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDocumentTreeItemResponseModel(value)) {
        return DocumentTreeItemResponseModelToJSON(value as DocumentTreeItemResponseModel);
    }

    return {};
}

