/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HealthCheckActionRequestModel } from './HealthCheckActionRequestModel';
import {
    instanceOfHealthCheckActionRequestModel,
    HealthCheckActionRequestModelFromJSON,
    HealthCheckActionRequestModelFromJSONTyped,
    HealthCheckActionRequestModelToJSON,
} from './HealthCheckActionRequestModel';

/**
 * @type HealthCheckResultResponseModelActionsInner
 * 
 * @export
 */
export type HealthCheckResultResponseModelActionsInner = HealthCheckActionRequestModel;

export function HealthCheckResultResponseModelActionsInnerFromJSON(json: any): HealthCheckResultResponseModelActionsInner {
    return HealthCheckResultResponseModelActionsInnerFromJSONTyped(json, false);
}

export function HealthCheckResultResponseModelActionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckResultResponseModelActionsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfHealthCheckActionRequestModel(json)) {
        return HealthCheckActionRequestModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function HealthCheckResultResponseModelActionsInnerToJSON(json: any): any {
    return HealthCheckResultResponseModelActionsInnerToJSONTyped(json, false);
}

export function HealthCheckResultResponseModelActionsInnerToJSONTyped(value?: HealthCheckResultResponseModelActionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfHealthCheckActionRequestModel(value)) {
        return HealthCheckActionRequestModelToJSON(value as HealthCheckActionRequestModel);
    }

    return {};
}

