/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HealthCheckResultResponseModel } from './HealthCheckResultResponseModel';
import {
    instanceOfHealthCheckResultResponseModel,
    HealthCheckResultResponseModelFromJSON,
    HealthCheckResultResponseModelFromJSONTyped,
    HealthCheckResultResponseModelToJSON,
} from './HealthCheckResultResponseModel';

/**
 * @type HealthCheckWithResultPresentationModelResultsInner
 * 
 * @export
 */
export type HealthCheckWithResultPresentationModelResultsInner = HealthCheckResultResponseModel;

export function HealthCheckWithResultPresentationModelResultsInnerFromJSON(json: any): HealthCheckWithResultPresentationModelResultsInner {
    return HealthCheckWithResultPresentationModelResultsInnerFromJSONTyped(json, false);
}

export function HealthCheckWithResultPresentationModelResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckWithResultPresentationModelResultsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfHealthCheckResultResponseModel(json)) {
        return HealthCheckResultResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function HealthCheckWithResultPresentationModelResultsInnerToJSON(json: any): any {
    return HealthCheckWithResultPresentationModelResultsInnerToJSONTyped(json, false);
}

export function HealthCheckWithResultPresentationModelResultsInnerToJSONTyped(value?: HealthCheckWithResultPresentationModelResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfHealthCheckResultResponseModel(value)) {
        return HealthCheckResultResponseModelToJSON(value as HealthCheckResultResponseModel);
    }

    return {};
}

