/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HealthStatusModel = {
    Healthy: 'Healthy',
    Unhealthy: 'Unhealthy',
    Rebuilding: 'Rebuilding',
    Corrupt: 'Corrupt'
} as const;
export type HealthStatusModel = typeof HealthStatusModel[keyof typeof HealthStatusModel];


export function instanceOfHealthStatusModel(value: any): boolean {
    for (const key in HealthStatusModel) {
        if (Object.prototype.hasOwnProperty.call(HealthStatusModel, key)) {
            if (HealthStatusModel[key as keyof typeof HealthStatusModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function HealthStatusModelFromJSON(json: any): HealthStatusModel {
    return HealthStatusModelFromJSONTyped(json, false);
}

export function HealthStatusModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthStatusModel {
    return json as HealthStatusModel;
}

export function HealthStatusModelToJSON(value?: HealthStatusModel | null): any {
    return value as any;
}

export function HealthStatusModelToJSONTyped(value: any, ignoreDiscriminator: boolean): HealthStatusModel {
    return value as HealthStatusModel;
}

