/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemReferenceByIdResponseModel
 */
export interface ItemReferenceByIdResponseModel {
    /**
     * 
     * @type {string}
     * @memberof ItemReferenceByIdResponseModel
     */
    id: string;
}

/**
 * Check if a given object implements the ItemReferenceByIdResponseModel interface.
 */
export function instanceOfItemReferenceByIdResponseModel(value: object): value is ItemReferenceByIdResponseModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ItemReferenceByIdResponseModelFromJSON(json: any): ItemReferenceByIdResponseModel {
    return ItemReferenceByIdResponseModelFromJSONTyped(json, false);
}

export function ItemReferenceByIdResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemReferenceByIdResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ItemReferenceByIdResponseModelToJSON(json: any): ItemReferenceByIdResponseModel {
    return ItemReferenceByIdResponseModelToJSONTyped(json, false);
}

export function ItemReferenceByIdResponseModelToJSONTyped(value?: ItemReferenceByIdResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

