/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaTypeCollectionReferenceResponseModel
 */
export interface MediaTypeCollectionReferenceResponseModel {
    /**
     * 
     * @type {string}
     * @memberof MediaTypeCollectionReferenceResponseModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MediaTypeCollectionReferenceResponseModel
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof MediaTypeCollectionReferenceResponseModel
     */
    icon: string;
}

/**
 * Check if a given object implements the MediaTypeCollectionReferenceResponseModel interface.
 */
export function instanceOfMediaTypeCollectionReferenceResponseModel(value: object): value is MediaTypeCollectionReferenceResponseModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    return true;
}

export function MediaTypeCollectionReferenceResponseModelFromJSON(json: any): MediaTypeCollectionReferenceResponseModel {
    return MediaTypeCollectionReferenceResponseModelFromJSONTyped(json, false);
}

export function MediaTypeCollectionReferenceResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaTypeCollectionReferenceResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'alias': json['alias'],
        'icon': json['icon'],
    };
}

export function MediaTypeCollectionReferenceResponseModelToJSON(json: any): MediaTypeCollectionReferenceResponseModel {
    return MediaTypeCollectionReferenceResponseModelToJSONTyped(json, false);
}

export function MediaTypeCollectionReferenceResponseModelToJSONTyped(value?: MediaTypeCollectionReferenceResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'alias': value['alias'],
        'icon': value['icon'],
    };
}

