/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaValueResponseModel
 */
export interface MediaValueResponseModel {
    /**
     * 
     * @type {string}
     * @memberof MediaValueResponseModel
     */
    culture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaValueResponseModel
     */
    segment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaValueResponseModel
     */
    alias: string;
    /**
     * 
     * @type {any}
     * @memberof MediaValueResponseModel
     */
    value?: any | null;
    /**
     * 
     * @type {string}
     * @memberof MediaValueResponseModel
     */
    editorAlias: string;
}

/**
 * Check if a given object implements the MediaValueResponseModel interface.
 */
export function instanceOfMediaValueResponseModel(value: object): value is MediaValueResponseModel {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('editorAlias' in value) || value['editorAlias'] === undefined) return false;
    return true;
}

export function MediaValueResponseModelFromJSON(json: any): MediaValueResponseModel {
    return MediaValueResponseModelFromJSONTyped(json, false);
}

export function MediaValueResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaValueResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'culture': json['culture'] == null ? undefined : json['culture'],
        'segment': json['segment'] == null ? undefined : json['segment'],
        'alias': json['alias'],
        'value': json['value'] == null ? undefined : json['value'],
        'editorAlias': json['editorAlias'],
    };
}

export function MediaValueResponseModelToJSON(json: any): MediaValueResponseModel {
    return MediaValueResponseModelToJSONTyped(json, false);
}

export function MediaValueResponseModelToJSONTyped(value?: MediaValueResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'culture': value['culture'],
        'segment': value['segment'],
        'alias': value['alias'],
        'value': value['value'],
        'editorAlias': value['editorAlias'],
    };
}

