/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaVariantResponseModel
 */
export interface MediaVariantResponseModel {
    /**
     * 
     * @type {string}
     * @memberof MediaVariantResponseModel
     */
    culture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaVariantResponseModel
     */
    segment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaVariantResponseModel
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof MediaVariantResponseModel
     */
    createDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof MediaVariantResponseModel
     */
    updateDate: Date;
}

/**
 * Check if a given object implements the MediaVariantResponseModel interface.
 */
export function instanceOfMediaVariantResponseModel(value: object): value is MediaVariantResponseModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createDate' in value) || value['createDate'] === undefined) return false;
    if (!('updateDate' in value) || value['updateDate'] === undefined) return false;
    return true;
}

export function MediaVariantResponseModelFromJSON(json: any): MediaVariantResponseModel {
    return MediaVariantResponseModelFromJSONTyped(json, false);
}

export function MediaVariantResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaVariantResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'culture': json['culture'] == null ? undefined : json['culture'],
        'segment': json['segment'] == null ? undefined : json['segment'],
        'name': json['name'],
        'createDate': (new Date(json['createDate'])),
        'updateDate': (new Date(json['updateDate'])),
    };
}

export function MediaVariantResponseModelToJSON(json: any): MediaVariantResponseModel {
    return MediaVariantResponseModelToJSONTyped(json, false);
}

export function MediaVariantResponseModelToJSONTyped(value?: MediaVariantResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'culture': value['culture'],
        'segment': value['segment'],
        'name': value['name'],
        'createDate': ((value['createDate']).toISOString()),
        'updateDate': ((value['updateDate']).toISOString()),
    };
}

