/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaValueModel
 */
export interface MediaValueModel {
    /**
     * 
     * @type {string}
     * @memberof MediaValueModel
     */
    culture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaValueModel
     */
    segment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaValueModel
     */
    alias: string;
    /**
     * 
     * @type {any}
     * @memberof MediaValueModel
     */
    value?: any | null;
}

/**
 * Check if a given object implements the MediaValueModel interface.
 */
export function instanceOfMediaValueModel(value: object): value is MediaValueModel {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    return true;
}

export function MediaValueModelFromJSON(json: any): MediaValueModel {
    return MediaValueModelFromJSONTyped(json, false);
}

export function MediaValueModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaValueModel {
    if (json == null) {
        return json;
    }
    return {
        
        'culture': json['culture'] == null ? undefined : json['culture'],
        'segment': json['segment'] == null ? undefined : json['segment'],
        'alias': json['alias'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MediaValueModelToJSON(json: any): MediaValueModel {
    return MediaValueModelToJSONTyped(json, false);
}

export function MediaValueModelToJSONTyped(value?: MediaValueModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'culture': value['culture'],
        'segment': value['segment'],
        'alias': value['alias'],
        'value': value['value'],
    };
}

