/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaConfigurationResponseModel
 */
export interface MediaConfigurationResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof MediaConfigurationResponseModel
     */
    disableDeleteWhenReferenced: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MediaConfigurationResponseModel
     */
    disableUnpublishWhenReferenced: boolean;
}

/**
 * Check if a given object implements the MediaConfigurationResponseModel interface.
 */
export function instanceOfMediaConfigurationResponseModel(value: object): value is MediaConfigurationResponseModel {
    if (!('disableDeleteWhenReferenced' in value) || value['disableDeleteWhenReferenced'] === undefined) return false;
    if (!('disableUnpublishWhenReferenced' in value) || value['disableUnpublishWhenReferenced'] === undefined) return false;
    return true;
}

export function MediaConfigurationResponseModelFromJSON(json: any): MediaConfigurationResponseModel {
    return MediaConfigurationResponseModelFromJSONTyped(json, false);
}

export function MediaConfigurationResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaConfigurationResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'disableDeleteWhenReferenced': json['disableDeleteWhenReferenced'],
        'disableUnpublishWhenReferenced': json['disableUnpublishWhenReferenced'],
    };
}

export function MediaConfigurationResponseModelToJSON(json: any): MediaConfigurationResponseModel {
    return MediaConfigurationResponseModelToJSONTyped(json, false);
}

export function MediaConfigurationResponseModelToJSONTyped(value?: MediaConfigurationResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disableDeleteWhenReferenced': value['disableDeleteWhenReferenced'],
        'disableUnpublishWhenReferenced': value['disableUnpublishWhenReferenced'],
    };
}

