/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberTypeConfigurationResponseModel
 */
export interface MemberTypeConfigurationResponseModel {
    /**
     * 
     * @type {Set<string>}
     * @memberof MemberTypeConfigurationResponseModel
     */
    reservedFieldNames: Set<string>;
}

/**
 * Check if a given object implements the MemberTypeConfigurationResponseModel interface.
 */
export function instanceOfMemberTypeConfigurationResponseModel(value: object): value is MemberTypeConfigurationResponseModel {
    if (!('reservedFieldNames' in value) || value['reservedFieldNames'] === undefined) return false;
    return true;
}

export function MemberTypeConfigurationResponseModelFromJSON(json: any): MemberTypeConfigurationResponseModel {
    return MemberTypeConfigurationResponseModelFromJSONTyped(json, false);
}

export function MemberTypeConfigurationResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberTypeConfigurationResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'reservedFieldNames': new Set(json['reservedFieldNames']),
    };
}

export function MemberTypeConfigurationResponseModelToJSON(json: any): MemberTypeConfigurationResponseModel {
    return MemberTypeConfigurationResponseModelToJSONTyped(json, false);
}

export function MemberTypeConfigurationResponseModelToJSONTyped(value?: MemberTypeConfigurationResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reservedFieldNames': Array.from(value['reservedFieldNames'] as Set<any>),
    };
}

