/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackedReferenceMemberTypeModel } from './TrackedReferenceMemberTypeModel';
import {
    TrackedReferenceMemberTypeModelFromJSON,
    TrackedReferenceMemberTypeModelFromJSONTyped,
    TrackedReferenceMemberTypeModelToJSON,
    TrackedReferenceMemberTypeModelToJSONTyped,
} from './TrackedReferenceMemberTypeModel';

/**
 * 
 * @export
 * @interface MemberTypePropertyTypeReferenceResponseModel
 */
export interface MemberTypePropertyTypeReferenceResponseModel {
    /**
     * 
     * @type {string}
     * @memberof MemberTypePropertyTypeReferenceResponseModel
     */
    $type: string;
    /**
     * 
     * @type {string}
     * @memberof MemberTypePropertyTypeReferenceResponseModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MemberTypePropertyTypeReferenceResponseModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MemberTypePropertyTypeReferenceResponseModel
     */
    alias?: string | null;
    /**
     * 
     * @type {TrackedReferenceMemberTypeModel}
     * @memberof MemberTypePropertyTypeReferenceResponseModel
     */
    memberType: TrackedReferenceMemberTypeModel;
}

/**
 * Check if a given object implements the MemberTypePropertyTypeReferenceResponseModel interface.
 */
export function instanceOfMemberTypePropertyTypeReferenceResponseModel(value: object): value is MemberTypePropertyTypeReferenceResponseModel {
    if (!('$type' in value) || value['$type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('memberType' in value) || value['memberType'] === undefined) return false;
    return true;
}

export function MemberTypePropertyTypeReferenceResponseModelFromJSON(json: any): MemberTypePropertyTypeReferenceResponseModel {
    return MemberTypePropertyTypeReferenceResponseModelFromJSONTyped(json, false);
}

export function MemberTypePropertyTypeReferenceResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberTypePropertyTypeReferenceResponseModel {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['$type'] === 'MemberTypePropertyTypeReferenceResponseModel') {
            return MemberTypePropertyTypeReferenceResponseModelFromJSONTyped(json, ignoreDiscriminator);
        }
    }
    return {
        
        '$type': json['$type'],
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'memberType': TrackedReferenceMemberTypeModelFromJSON(json['memberType']),
    };
}

export function MemberTypePropertyTypeReferenceResponseModelToJSON(json: any): MemberTypePropertyTypeReferenceResponseModel {
    return MemberTypePropertyTypeReferenceResponseModelToJSONTyped(json, false);
}

export function MemberTypePropertyTypeReferenceResponseModelToJSONTyped(value?: MemberTypePropertyTypeReferenceResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['$type']) {
            case 'MemberTypePropertyTypeReferenceResponseModel':
                return MemberTypePropertyTypeReferenceResponseModelToJSONTyped(value as MemberTypePropertyTypeReferenceResponseModel, ignoreDiscriminator);
            default:
                return value;
        }
    }

    return {
        
        '$type': value['$type'],
        'id': value['id'],
        'name': value['name'],
        'alias': value['alias'],
        'memberType': TrackedReferenceMemberTypeModelToJSON(value['memberType']),
    };
}

