/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceByIdModel } from './ReferenceByIdModel';
import {
    ReferenceByIdModelFromJSON,
    ReferenceByIdModelFromJSONTyped,
    ReferenceByIdModelToJSON,
    ReferenceByIdModelToJSONTyped,
} from './ReferenceByIdModel';

/**
 * 
 * @export
 * @interface MoveDocumentTypeRequestModel
 */
export interface MoveDocumentTypeRequestModel {
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof MoveDocumentTypeRequestModel
     */
    target?: ReferenceByIdModel | null;
}

/**
 * Check if a given object implements the MoveDocumentTypeRequestModel interface.
 */
export function instanceOfMoveDocumentTypeRequestModel(value: object): value is MoveDocumentTypeRequestModel {
    return true;
}

export function MoveDocumentTypeRequestModelFromJSON(json: any): MoveDocumentTypeRequestModel {
    return MoveDocumentTypeRequestModelFromJSONTyped(json, false);
}

export function MoveDocumentTypeRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveDocumentTypeRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'target': json['target'] == null ? undefined : ReferenceByIdModelFromJSON(json['target']),
    };
}

export function MoveDocumentTypeRequestModelToJSON(json: any): MoveDocumentTypeRequestModel {
    return MoveDocumentTypeRequestModelToJSONTyped(json, false);
}

export function MoveDocumentTypeRequestModelToJSONTyped(value?: MoveDocumentTypeRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target': ReferenceByIdModelToJSON(value['target']),
    };
}

