/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceByIdModel } from './ReferenceByIdModel';
import {
    ReferenceByIdModelFromJSON,
    ReferenceByIdModelFromJSONTyped,
    ReferenceByIdModelToJSON,
    ReferenceByIdModelToJSONTyped,
} from './ReferenceByIdModel';

/**
 * 
 * @export
 * @interface MoveDataTypeRequestModel
 */
export interface MoveDataTypeRequestModel {
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof MoveDataTypeRequestModel
     */
    target?: ReferenceByIdModel | null;
}

/**
 * Check if a given object implements the MoveDataTypeRequestModel interface.
 */
export function instanceOfMoveDataTypeRequestModel(value: object): value is MoveDataTypeRequestModel {
    return true;
}

export function MoveDataTypeRequestModelFromJSON(json: any): MoveDataTypeRequestModel {
    return MoveDataTypeRequestModelFromJSONTyped(json, false);
}

export function MoveDataTypeRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveDataTypeRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'target': json['target'] == null ? undefined : ReferenceByIdModelFromJSON(json['target']),
    };
}

export function MoveDataTypeRequestModelToJSON(json: any): MoveDataTypeRequestModel {
    return MoveDataTypeRequestModelToJSONTyped(json, false);
}

export function MoveDataTypeRequestModelToJSONTyped(value?: MoveDataTypeRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target': ReferenceByIdModelToJSON(value['target']),
    };
}

