/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetTreeDictionaryAncestors200ResponseInner } from './GetTreeDictionaryAncestors200ResponseInner';
import {
    GetTreeDictionaryAncestors200ResponseInnerFromJSON,
    GetTreeDictionaryAncestors200ResponseInnerFromJSONTyped,
    GetTreeDictionaryAncestors200ResponseInnerToJSON,
    GetTreeDictionaryAncestors200ResponseInnerToJSONTyped,
} from './GetTreeDictionaryAncestors200ResponseInner';

/**
 * 
 * @export
 * @interface PagedNamedEntityTreeItemResponseModel
 */
export interface PagedNamedEntityTreeItemResponseModel {
    /**
     * 
     * @type {number}
     * @memberof PagedNamedEntityTreeItemResponseModel
     */
    total: number;
    /**
     * 
     * @type {Array<GetTreeDictionaryAncestors200ResponseInner>}
     * @memberof PagedNamedEntityTreeItemResponseModel
     */
    items: Array<GetTreeDictionaryAncestors200ResponseInner>;
}

/**
 * Check if a given object implements the PagedNamedEntityTreeItemResponseModel interface.
 */
export function instanceOfPagedNamedEntityTreeItemResponseModel(value: object): value is PagedNamedEntityTreeItemResponseModel {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PagedNamedEntityTreeItemResponseModelFromJSON(json: any): PagedNamedEntityTreeItemResponseModel {
    return PagedNamedEntityTreeItemResponseModelFromJSONTyped(json, false);
}

export function PagedNamedEntityTreeItemResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedNamedEntityTreeItemResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(GetTreeDictionaryAncestors200ResponseInnerFromJSON)),
    };
}

export function PagedNamedEntityTreeItemResponseModelToJSON(json: any): PagedNamedEntityTreeItemResponseModel {
    return PagedNamedEntityTreeItemResponseModelToJSONTyped(json, false);
}

export function PagedNamedEntityTreeItemResponseModelToJSONTyped(value?: PagedNamedEntityTreeItemResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(GetTreeDictionaryAncestors200ResponseInnerToJSON)),
    };
}

