/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedCultureReponseModelItemsInner } from './PagedCultureReponseModelItemsInner';
import {
    PagedCultureReponseModelItemsInnerFromJSON,
    PagedCultureReponseModelItemsInnerFromJSONTyped,
    PagedCultureReponseModelItemsInnerToJSON,
    PagedCultureReponseModelItemsInnerToJSONTyped,
} from './PagedCultureReponseModelItemsInner';

/**
 * 
 * @export
 * @interface PagedCultureReponseModel
 */
export interface PagedCultureReponseModel {
    /**
     * 
     * @type {number}
     * @memberof PagedCultureReponseModel
     */
    total: number;
    /**
     * 
     * @type {Array<PagedCultureReponseModelItemsInner>}
     * @memberof PagedCultureReponseModel
     */
    items: Array<PagedCultureReponseModelItemsInner>;
}

/**
 * Check if a given object implements the PagedCultureReponseModel interface.
 */
export function instanceOfPagedCultureReponseModel(value: object): value is PagedCultureReponseModel {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PagedCultureReponseModelFromJSON(json: any): PagedCultureReponseModel {
    return PagedCultureReponseModelFromJSONTyped(json, false);
}

export function PagedCultureReponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedCultureReponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(PagedCultureReponseModelItemsInnerFromJSON)),
    };
}

export function PagedCultureReponseModelToJSON(json: any): PagedCultureReponseModel {
    return PagedCultureReponseModelToJSONTyped(json, false);
}

export function PagedCultureReponseModelToJSONTyped(value?: PagedCultureReponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(PagedCultureReponseModelItemsInnerToJSON)),
    };
}

