/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedLogMessageResponseModelItemsInner } from './PagedLogMessageResponseModelItemsInner';
import {
    PagedLogMessageResponseModelItemsInnerFromJSON,
    PagedLogMessageResponseModelItemsInnerFromJSONTyped,
    PagedLogMessageResponseModelItemsInnerToJSON,
    PagedLogMessageResponseModelItemsInnerToJSONTyped,
} from './PagedLogMessageResponseModelItemsInner';

/**
 * 
 * @export
 * @interface PagedLogMessageResponseModel
 */
export interface PagedLogMessageResponseModel {
    /**
     * 
     * @type {number}
     * @memberof PagedLogMessageResponseModel
     */
    total: number;
    /**
     * 
     * @type {Array<PagedLogMessageResponseModelItemsInner>}
     * @memberof PagedLogMessageResponseModel
     */
    items: Array<PagedLogMessageResponseModelItemsInner>;
}

/**
 * Check if a given object implements the PagedLogMessageResponseModel interface.
 */
export function instanceOfPagedLogMessageResponseModel(value: object): value is PagedLogMessageResponseModel {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PagedLogMessageResponseModelFromJSON(json: any): PagedLogMessageResponseModel {
    return PagedLogMessageResponseModelFromJSONTyped(json, false);
}

export function PagedLogMessageResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedLogMessageResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(PagedLogMessageResponseModelItemsInnerFromJSON)),
    };
}

export function PagedLogMessageResponseModelToJSON(json: any): PagedLogMessageResponseModel {
    return PagedLogMessageResponseModelToJSONTyped(json, false);
}

export function PagedLogMessageResponseModelToJSONTyped(value?: PagedLogMessageResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(PagedLogMessageResponseModelItemsInnerToJSON)),
    };
}

