/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetItemTemplate200ResponseInner } from './GetItemTemplate200ResponseInner';
import {
    GetItemTemplate200ResponseInnerFromJSON,
    GetItemTemplate200ResponseInnerFromJSONTyped,
    GetItemTemplate200ResponseInnerToJSON,
    GetItemTemplate200ResponseInnerToJSONTyped,
} from './GetItemTemplate200ResponseInner';

/**
 * 
 * @export
 * @interface PagedModelTemplateItemResponseModel
 */
export interface PagedModelTemplateItemResponseModel {
    /**
     * 
     * @type {Array<GetItemTemplate200ResponseInner>}
     * @memberof PagedModelTemplateItemResponseModel
     */
    items: Array<GetItemTemplate200ResponseInner>;
    /**
     * 
     * @type {number}
     * @memberof PagedModelTemplateItemResponseModel
     */
    total: number;
}

/**
 * Check if a given object implements the PagedModelTemplateItemResponseModel interface.
 */
export function instanceOfPagedModelTemplateItemResponseModel(value: object): value is PagedModelTemplateItemResponseModel {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PagedModelTemplateItemResponseModelFromJSON(json: any): PagedModelTemplateItemResponseModel {
    return PagedModelTemplateItemResponseModelFromJSONTyped(json, false);
}

export function PagedModelTemplateItemResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelTemplateItemResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GetItemTemplate200ResponseInnerFromJSON)),
        'total': json['total'],
    };
}

export function PagedModelTemplateItemResponseModelToJSON(json: any): PagedModelTemplateItemResponseModel {
    return PagedModelTemplateItemResponseModelToJSONTyped(json, false);
}

export function PagedModelTemplateItemResponseModelToJSONTyped(value?: PagedModelTemplateItemResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(GetItemTemplate200ResponseInnerToJSON)),
        'total': value['total'],
    };
}

