/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedRelationResponseModelItemsInner } from './PagedRelationResponseModelItemsInner';
import {
    PagedRelationResponseModelItemsInnerFromJSON,
    PagedRelationResponseModelItemsInnerFromJSONTyped,
    PagedRelationResponseModelItemsInnerToJSON,
    PagedRelationResponseModelItemsInnerToJSONTyped,
} from './PagedRelationResponseModelItemsInner';

/**
 * 
 * @export
 * @interface PagedRelationResponseModel
 */
export interface PagedRelationResponseModel {
    /**
     * 
     * @type {number}
     * @memberof PagedRelationResponseModel
     */
    total: number;
    /**
     * 
     * @type {Array<PagedRelationResponseModelItemsInner>}
     * @memberof PagedRelationResponseModel
     */
    items: Array<PagedRelationResponseModelItemsInner>;
}

/**
 * Check if a given object implements the PagedRelationResponseModel interface.
 */
export function instanceOfPagedRelationResponseModel(value: object): value is PagedRelationResponseModel {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PagedRelationResponseModelFromJSON(json: any): PagedRelationResponseModel {
    return PagedRelationResponseModelFromJSONTyped(json, false);
}

export function PagedRelationResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedRelationResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(PagedRelationResponseModelItemsInnerFromJSON)),
    };
}

export function PagedRelationResponseModelToJSON(json: any): PagedRelationResponseModel {
    return PagedRelationResponseModelToJSONTyped(json, false);
}

export function PagedRelationResponseModelToJSONTyped(value?: PagedRelationResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(PagedRelationResponseModelItemsInnerToJSON)),
    };
}

