/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedMediaCollectionResponseModelItemsInner } from './PagedMediaCollectionResponseModelItemsInner';
import {
    PagedMediaCollectionResponseModelItemsInnerFromJSON,
    PagedMediaCollectionResponseModelItemsInnerFromJSONTyped,
    PagedMediaCollectionResponseModelItemsInnerToJSON,
    PagedMediaCollectionResponseModelItemsInnerToJSONTyped,
} from './PagedMediaCollectionResponseModelItemsInner';

/**
 * 
 * @export
 * @interface PagedMediaCollectionResponseModel
 */
export interface PagedMediaCollectionResponseModel {
    /**
     * 
     * @type {number}
     * @memberof PagedMediaCollectionResponseModel
     */
    total: number;
    /**
     * 
     * @type {Array<PagedMediaCollectionResponseModelItemsInner>}
     * @memberof PagedMediaCollectionResponseModel
     */
    items: Array<PagedMediaCollectionResponseModelItemsInner>;
}

/**
 * Check if a given object implements the PagedMediaCollectionResponseModel interface.
 */
export function instanceOfPagedMediaCollectionResponseModel(value: object): value is PagedMediaCollectionResponseModel {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PagedMediaCollectionResponseModelFromJSON(json: any): PagedMediaCollectionResponseModel {
    return PagedMediaCollectionResponseModelFromJSONTyped(json, false);
}

export function PagedMediaCollectionResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedMediaCollectionResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(PagedMediaCollectionResponseModelItemsInnerFromJSON)),
    };
}

export function PagedMediaCollectionResponseModelToJSON(json: any): PagedMediaCollectionResponseModel {
    return PagedMediaCollectionResponseModelToJSONTyped(json, false);
}

export function PagedMediaCollectionResponseModelToJSONTyped(value?: PagedMediaCollectionResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(PagedMediaCollectionResponseModelItemsInnerToJSON)),
    };
}

