/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MemberTypeTreeItemResponseModel } from './MemberTypeTreeItemResponseModel';
import {
    instanceOfMemberTypeTreeItemResponseModel,
    MemberTypeTreeItemResponseModelFromJSON,
    MemberTypeTreeItemResponseModelFromJSONTyped,
    MemberTypeTreeItemResponseModelToJSON,
} from './MemberTypeTreeItemResponseModel';

/**
 * @type PagedMemberTypeTreeItemResponseModelItemsInner
 * 
 * @export
 */
export type PagedMemberTypeTreeItemResponseModelItemsInner = MemberTypeTreeItemResponseModel;

export function PagedMemberTypeTreeItemResponseModelItemsInnerFromJSON(json: any): PagedMemberTypeTreeItemResponseModelItemsInner {
    return PagedMemberTypeTreeItemResponseModelItemsInnerFromJSONTyped(json, false);
}

export function PagedMemberTypeTreeItemResponseModelItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedMemberTypeTreeItemResponseModelItemsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfMemberTypeTreeItemResponseModel(json)) {
        return MemberTypeTreeItemResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function PagedMemberTypeTreeItemResponseModelItemsInnerToJSON(json: any): any {
    return PagedMemberTypeTreeItemResponseModelItemsInnerToJSONTyped(json, false);
}

export function PagedMemberTypeTreeItemResponseModelItemsInnerToJSONTyped(value?: PagedMemberTypeTreeItemResponseModelItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfMemberTypeTreeItemResponseModel(value)) {
        return MemberTypeTreeItemResponseModelToJSON(value as MemberTypeTreeItemResponseModel);
    }

    return {};
}

