/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedTelemetryResponseModelItemsInner } from './PagedTelemetryResponseModelItemsInner';
import {
    PagedTelemetryResponseModelItemsInnerFromJSON,
    PagedTelemetryResponseModelItemsInnerFromJSONTyped,
    PagedTelemetryResponseModelItemsInnerToJSON,
    PagedTelemetryResponseModelItemsInnerToJSONTyped,
} from './PagedTelemetryResponseModelItemsInner';

/**
 * 
 * @export
 * @interface PagedTelemetryResponseModel
 */
export interface PagedTelemetryResponseModel {
    /**
     * 
     * @type {number}
     * @memberof PagedTelemetryResponseModel
     */
    total: number;
    /**
     * 
     * @type {Array<PagedTelemetryResponseModelItemsInner>}
     * @memberof PagedTelemetryResponseModel
     */
    items: Array<PagedTelemetryResponseModelItemsInner>;
}

/**
 * Check if a given object implements the PagedTelemetryResponseModel interface.
 */
export function instanceOfPagedTelemetryResponseModel(value: object): value is PagedTelemetryResponseModel {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PagedTelemetryResponseModelFromJSON(json: any): PagedTelemetryResponseModel {
    return PagedTelemetryResponseModelFromJSONTyped(json, false);
}

export function PagedTelemetryResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedTelemetryResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(PagedTelemetryResponseModelItemsInnerFromJSON)),
    };
}

export function PagedTelemetryResponseModelToJSON(json: any): PagedTelemetryResponseModel {
    return PagedTelemetryResponseModelToJSONTyped(json, false);
}

export function PagedTelemetryResponseModelToJSONTyped(value?: PagedTelemetryResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(PagedTelemetryResponseModelItemsInnerToJSON)),
    };
}

