/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedIndexResponseModelItemsInner } from './PagedIndexResponseModelItemsInner';
import {
    PagedIndexResponseModelItemsInnerFromJSON,
    PagedIndexResponseModelItemsInnerFromJSONTyped,
    PagedIndexResponseModelItemsInnerToJSON,
    PagedIndexResponseModelItemsInnerToJSONTyped,
} from './PagedIndexResponseModelItemsInner';

/**
 * 
 * @export
 * @interface PagedIndexResponseModel
 */
export interface PagedIndexResponseModel {
    /**
     * 
     * @type {number}
     * @memberof PagedIndexResponseModel
     */
    total: number;
    /**
     * 
     * @type {Array<PagedIndexResponseModelItemsInner>}
     * @memberof PagedIndexResponseModel
     */
    items: Array<PagedIndexResponseModelItemsInner>;
}

/**
 * Check if a given object implements the PagedIndexResponseModel interface.
 */
export function instanceOfPagedIndexResponseModel(value: object): value is PagedIndexResponseModel {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PagedIndexResponseModelFromJSON(json: any): PagedIndexResponseModel {
    return PagedIndexResponseModelFromJSONTyped(json, false);
}

export function PagedIndexResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedIndexResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(PagedIndexResponseModelItemsInnerFromJSON)),
    };
}

export function PagedIndexResponseModelToJSON(json: any): PagedIndexResponseModel {
    return PagedIndexResponseModelToJSONTyped(json, false);
}

export function PagedIndexResponseModelToJSONTyped(value?: PagedIndexResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(PagedIndexResponseModelItemsInnerToJSON)),
    };
}

