/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedAllowedMediaTypeModelItemsInner } from './PagedAllowedMediaTypeModelItemsInner';
import {
    PagedAllowedMediaTypeModelItemsInnerFromJSON,
    PagedAllowedMediaTypeModelItemsInnerFromJSONTyped,
    PagedAllowedMediaTypeModelItemsInnerToJSON,
    PagedAllowedMediaTypeModelItemsInnerToJSONTyped,
} from './PagedAllowedMediaTypeModelItemsInner';

/**
 * 
 * @export
 * @interface PagedAllowedMediaTypeModel
 */
export interface PagedAllowedMediaTypeModel {
    /**
     * 
     * @type {number}
     * @memberof PagedAllowedMediaTypeModel
     */
    total: number;
    /**
     * 
     * @type {Array<PagedAllowedMediaTypeModelItemsInner>}
     * @memberof PagedAllowedMediaTypeModel
     */
    items: Array<PagedAllowedMediaTypeModelItemsInner>;
}

/**
 * Check if a given object implements the PagedAllowedMediaTypeModel interface.
 */
export function instanceOfPagedAllowedMediaTypeModel(value: object): value is PagedAllowedMediaTypeModel {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PagedAllowedMediaTypeModelFromJSON(json: any): PagedAllowedMediaTypeModel {
    return PagedAllowedMediaTypeModelFromJSONTyped(json, false);
}

export function PagedAllowedMediaTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedAllowedMediaTypeModel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(PagedAllowedMediaTypeModelItemsInnerFromJSON)),
    };
}

export function PagedAllowedMediaTypeModelToJSON(json: any): PagedAllowedMediaTypeModel {
    return PagedAllowedMediaTypeModelToJSONTyped(json, false);
}

export function PagedAllowedMediaTypeModelToJSONTyped(value?: PagedAllowedMediaTypeModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(PagedAllowedMediaTypeModelItemsInnerToJSON)),
    };
}

