/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MediaCollectionResponseModel } from './MediaCollectionResponseModel';
import {
    instanceOfMediaCollectionResponseModel,
    MediaCollectionResponseModelFromJSON,
    MediaCollectionResponseModelFromJSONTyped,
    MediaCollectionResponseModelToJSON,
} from './MediaCollectionResponseModel';

/**
 * @type PagedMediaCollectionResponseModelItemsInner
 * 
 * @export
 */
export type PagedMediaCollectionResponseModelItemsInner = MediaCollectionResponseModel;

export function PagedMediaCollectionResponseModelItemsInnerFromJSON(json: any): PagedMediaCollectionResponseModelItemsInner {
    return PagedMediaCollectionResponseModelItemsInnerFromJSONTyped(json, false);
}

export function PagedMediaCollectionResponseModelItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedMediaCollectionResponseModelItemsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfMediaCollectionResponseModel(json)) {
        return MediaCollectionResponseModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function PagedMediaCollectionResponseModelItemsInnerToJSON(json: any): any {
    return PagedMediaCollectionResponseModelItemsInnerToJSONTyped(json, false);
}

export function PagedMediaCollectionResponseModelItemsInnerToJSONTyped(value?: PagedMediaCollectionResponseModelItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfMediaCollectionResponseModel(value)) {
        return MediaCollectionResponseModelToJSON(value as MediaCollectionResponseModel);
    }

    return {};
}

