/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedPartialViewSnippetItemResponseModelItemsInner } from './PagedPartialViewSnippetItemResponseModelItemsInner';
import {
    PagedPartialViewSnippetItemResponseModelItemsInnerFromJSON,
    PagedPartialViewSnippetItemResponseModelItemsInnerFromJSONTyped,
    PagedPartialViewSnippetItemResponseModelItemsInnerToJSON,
    PagedPartialViewSnippetItemResponseModelItemsInnerToJSONTyped,
} from './PagedPartialViewSnippetItemResponseModelItemsInner';

/**
 * 
 * @export
 * @interface PagedPartialViewSnippetItemResponseModel
 */
export interface PagedPartialViewSnippetItemResponseModel {
    /**
     * 
     * @type {number}
     * @memberof PagedPartialViewSnippetItemResponseModel
     */
    total: number;
    /**
     * 
     * @type {Array<PagedPartialViewSnippetItemResponseModelItemsInner>}
     * @memberof PagedPartialViewSnippetItemResponseModel
     */
    items: Array<PagedPartialViewSnippetItemResponseModelItemsInner>;
}

/**
 * Check if a given object implements the PagedPartialViewSnippetItemResponseModel interface.
 */
export function instanceOfPagedPartialViewSnippetItemResponseModel(value: object): value is PagedPartialViewSnippetItemResponseModel {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PagedPartialViewSnippetItemResponseModelFromJSON(json: any): PagedPartialViewSnippetItemResponseModel {
    return PagedPartialViewSnippetItemResponseModelFromJSONTyped(json, false);
}

export function PagedPartialViewSnippetItemResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedPartialViewSnippetItemResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(PagedPartialViewSnippetItemResponseModelItemsInnerFromJSON)),
    };
}

export function PagedPartialViewSnippetItemResponseModelToJSON(json: any): PagedPartialViewSnippetItemResponseModel {
    return PagedPartialViewSnippetItemResponseModelToJSONTyped(json, false);
}

export function PagedPartialViewSnippetItemResponseModelToJSONTyped(value?: PagedPartialViewSnippetItemResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(PagedPartialViewSnippetItemResponseModelItemsInnerToJSON)),
    };
}

