/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ReferenceByIdModel } from './ReferenceByIdModel';
import {
    instanceOfReferenceByIdModel,
    ReferenceByIdModelFromJSON,
    ReferenceByIdModelFromJSONTyped,
    ReferenceByIdModelToJSON,
} from './ReferenceByIdModel';

/**
 * @type PostUserGroupByIdUsersRequestInner
 * 
 * @export
 */
export type PostUserGroupByIdUsersRequestInner = ReferenceByIdModel;

export function PostUserGroupByIdUsersRequestInnerFromJSON(json: any): PostUserGroupByIdUsersRequestInner {
    return PostUserGroupByIdUsersRequestInnerFromJSONTyped(json, false);
}

export function PostUserGroupByIdUsersRequestInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUserGroupByIdUsersRequestInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfReferenceByIdModel(json)) {
        return ReferenceByIdModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function PostUserGroupByIdUsersRequestInnerToJSON(json: any): any {
    return PostUserGroupByIdUsersRequestInnerToJSONTyped(json, false);
}

export function PostUserGroupByIdUsersRequestInnerToJSONTyped(value?: PostUserGroupByIdUsersRequestInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfReferenceByIdModel(value)) {
        return ReferenceByIdModelToJSON(value as ReferenceByIdModel);
    }

    return {};
}

