/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceByIdModel } from './ReferenceByIdModel';
import {
    ReferenceByIdModelFromJSON,
    ReferenceByIdModelFromJSONTyped,
    ReferenceByIdModelToJSON,
    ReferenceByIdModelToJSONTyped,
} from './ReferenceByIdModel';

/**
 * 
 * @export
 * @interface PublicAccessRequestModel
 */
export interface PublicAccessRequestModel {
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof PublicAccessRequestModel
     */
    loginDocument: ReferenceByIdModel;
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof PublicAccessRequestModel
     */
    errorDocument: ReferenceByIdModel;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublicAccessRequestModel
     */
    memberUserNames: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublicAccessRequestModel
     */
    memberGroupNames: Array<string>;
}

/**
 * Check if a given object implements the PublicAccessRequestModel interface.
 */
export function instanceOfPublicAccessRequestModel(value: object): value is PublicAccessRequestModel {
    if (!('loginDocument' in value) || value['loginDocument'] === undefined) return false;
    if (!('errorDocument' in value) || value['errorDocument'] === undefined) return false;
    if (!('memberUserNames' in value) || value['memberUserNames'] === undefined) return false;
    if (!('memberGroupNames' in value) || value['memberGroupNames'] === undefined) return false;
    return true;
}

export function PublicAccessRequestModelFromJSON(json: any): PublicAccessRequestModel {
    return PublicAccessRequestModelFromJSONTyped(json, false);
}

export function PublicAccessRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicAccessRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'loginDocument': ReferenceByIdModelFromJSON(json['loginDocument']),
        'errorDocument': ReferenceByIdModelFromJSON(json['errorDocument']),
        'memberUserNames': json['memberUserNames'],
        'memberGroupNames': json['memberGroupNames'],
    };
}

export function PublicAccessRequestModelToJSON(json: any): PublicAccessRequestModel {
    return PublicAccessRequestModelToJSONTyped(json, false);
}

export function PublicAccessRequestModelToJSONTyped(value?: PublicAccessRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'loginDocument': ReferenceByIdModelToJSON(value['loginDocument']),
        'errorDocument': ReferenceByIdModelToJSON(value['errorDocument']),
        'memberUserNames': value['memberUserNames'],
        'memberGroupNames': value['memberGroupNames'],
    };
}

