/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenameStylesheetRequestModel
 */
export interface RenameStylesheetRequestModel {
    /**
     * 
     * @type {string}
     * @memberof RenameStylesheetRequestModel
     */
    name: string;
}

/**
 * Check if a given object implements the RenameStylesheetRequestModel interface.
 */
export function instanceOfRenameStylesheetRequestModel(value: object): value is RenameStylesheetRequestModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RenameStylesheetRequestModelFromJSON(json: any): RenameStylesheetRequestModel {
    return RenameStylesheetRequestModelFromJSONTyped(json, false);
}

export function RenameStylesheetRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameStylesheetRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function RenameStylesheetRequestModelToJSON(json: any): RenameStylesheetRequestModel {
    return RenameStylesheetRequestModelToJSONTyped(json, false);
}

export function RenameStylesheetRequestModelToJSONTyped(value?: RenameStylesheetRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

