/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenameScriptRequestModel
 */
export interface RenameScriptRequestModel {
    /**
     * 
     * @type {string}
     * @memberof RenameScriptRequestModel
     */
    name: string;
}

/**
 * Check if a given object implements the RenameScriptRequestModel interface.
 */
export function instanceOfRenameScriptRequestModel(value: object): value is RenameScriptRequestModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RenameScriptRequestModelFromJSON(json: any): RenameScriptRequestModel {
    return RenameScriptRequestModelFromJSONTyped(json, false);
}

export function RenameScriptRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameScriptRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function RenameScriptRequestModelToJSON(json: any): RenameScriptRequestModel {
    return RenameScriptRequestModelToJSONTyped(json, false);
}

export function RenameScriptRequestModelToJSONTyped(value?: RenameScriptRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

