/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SavedLogSearchResponseModel
 */
export interface SavedLogSearchResponseModel {
    /**
     * 
     * @type {string}
     * @memberof SavedLogSearchResponseModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SavedLogSearchResponseModel
     */
    query: string;
}

/**
 * Check if a given object implements the SavedLogSearchResponseModel interface.
 */
export function instanceOfSavedLogSearchResponseModel(value: object): value is SavedLogSearchResponseModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function SavedLogSearchResponseModelFromJSON(json: any): SavedLogSearchResponseModel {
    return SavedLogSearchResponseModelFromJSONTyped(json, false);
}

export function SavedLogSearchResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SavedLogSearchResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'query': json['query'],
    };
}

export function SavedLogSearchResponseModelToJSON(json: any): SavedLogSearchResponseModel {
    return SavedLogSearchResponseModelToJSONTyped(json, false);
}

export function SavedLogSearchResponseModelToJSONTyped(value?: SavedLogSearchResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'query': value['query'],
    };
}

