/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceByIdModel } from './ReferenceByIdModel';
import {
    ReferenceByIdModelFromJSON,
    ReferenceByIdModelFromJSONTyped,
    ReferenceByIdModelToJSON,
    ReferenceByIdModelToJSONTyped,
} from './ReferenceByIdModel';

/**
 * 
 * @export
 * @interface TemplateResponseModel
 */
export interface TemplateResponseModel {
    /**
     * 
     * @type {string}
     * @memberof TemplateResponseModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateResponseModel
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateResponseModel
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateResponseModel
     */
    id: string;
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof TemplateResponseModel
     */
    masterTemplate?: ReferenceByIdModel | null;
}

/**
 * Check if a given object implements the TemplateResponseModel interface.
 */
export function instanceOfTemplateResponseModel(value: object): value is TemplateResponseModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function TemplateResponseModelFromJSON(json: any): TemplateResponseModel {
    return TemplateResponseModelFromJSONTyped(json, false);
}

export function TemplateResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'alias': json['alias'],
        'content': json['content'] == null ? undefined : json['content'],
        'id': json['id'],
        'masterTemplate': json['masterTemplate'] == null ? undefined : ReferenceByIdModelFromJSON(json['masterTemplate']),
    };
}

export function TemplateResponseModelToJSON(json: any): TemplateResponseModel {
    return TemplateResponseModelToJSONTyped(json, false);
}

export function TemplateResponseModelToJSONTyped(value?: TemplateResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'alias': value['alias'],
        'content': value['content'],
        'id': value['id'],
        'masterTemplate': ReferenceByIdModelToJSON(value['masterTemplate']),
    };
}

