/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMemberGroupRequestModel
 */
export interface UpdateMemberGroupRequestModel {
    /**
     * 
     * @type {string}
     * @memberof UpdateMemberGroupRequestModel
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateMemberGroupRequestModel interface.
 */
export function instanceOfUpdateMemberGroupRequestModel(value: object): value is UpdateMemberGroupRequestModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateMemberGroupRequestModelFromJSON(json: any): UpdateMemberGroupRequestModel {
    return UpdateMemberGroupRequestModelFromJSONTyped(json, false);
}

export function UpdateMemberGroupRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMemberGroupRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateMemberGroupRequestModelToJSON(json: any): UpdateMemberGroupRequestModel {
    return UpdateMemberGroupRequestModelToJSONTyped(json, false);
}

export function UpdateMemberGroupRequestModelToJSONTyped(value?: UpdateMemberGroupRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

