/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyTypeValidationModel } from './PropertyTypeValidationModel';
import {
    PropertyTypeValidationModelFromJSON,
    PropertyTypeValidationModelFromJSONTyped,
    PropertyTypeValidationModelToJSON,
    PropertyTypeValidationModelToJSONTyped,
} from './PropertyTypeValidationModel';
import type { MemberTypePropertyTypeVisibilityModel } from './MemberTypePropertyTypeVisibilityModel';
import {
    MemberTypePropertyTypeVisibilityModelFromJSON,
    MemberTypePropertyTypeVisibilityModelFromJSONTyped,
    MemberTypePropertyTypeVisibilityModelToJSON,
    MemberTypePropertyTypeVisibilityModelToJSONTyped,
} from './MemberTypePropertyTypeVisibilityModel';
import type { PropertyTypeAppearanceModel } from './PropertyTypeAppearanceModel';
import {
    PropertyTypeAppearanceModelFromJSON,
    PropertyTypeAppearanceModelFromJSONTyped,
    PropertyTypeAppearanceModelToJSON,
    PropertyTypeAppearanceModelToJSONTyped,
} from './PropertyTypeAppearanceModel';
import type { ReferenceByIdModel } from './ReferenceByIdModel';
import {
    ReferenceByIdModelFromJSON,
    ReferenceByIdModelFromJSONTyped,
    ReferenceByIdModelToJSON,
    ReferenceByIdModelToJSONTyped,
} from './ReferenceByIdModel';

/**
 * 
 * @export
 * @interface UpdateMemberTypePropertyTypeRequestModel
 */
export interface UpdateMemberTypePropertyTypeRequestModel {
    /**
     * 
     * @type {string}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    id: string;
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    container?: ReferenceByIdModel | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    sortOrder: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    description?: string | null;
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    dataType: ReferenceByIdModel;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    variesByCulture: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    variesBySegment: boolean;
    /**
     * 
     * @type {PropertyTypeValidationModel}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    validation: PropertyTypeValidationModel;
    /**
     * 
     * @type {PropertyTypeAppearanceModel}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    appearance: PropertyTypeAppearanceModel;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    isSensitive: boolean;
    /**
     * 
     * @type {MemberTypePropertyTypeVisibilityModel}
     * @memberof UpdateMemberTypePropertyTypeRequestModel
     */
    visibility: MemberTypePropertyTypeVisibilityModel;
}

/**
 * Check if a given object implements the UpdateMemberTypePropertyTypeRequestModel interface.
 */
export function instanceOfUpdateMemberTypePropertyTypeRequestModel(value: object): value is UpdateMemberTypePropertyTypeRequestModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    if (!('variesByCulture' in value) || value['variesByCulture'] === undefined) return false;
    if (!('variesBySegment' in value) || value['variesBySegment'] === undefined) return false;
    if (!('validation' in value) || value['validation'] === undefined) return false;
    if (!('appearance' in value) || value['appearance'] === undefined) return false;
    if (!('isSensitive' in value) || value['isSensitive'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function UpdateMemberTypePropertyTypeRequestModelFromJSON(json: any): UpdateMemberTypePropertyTypeRequestModel {
    return UpdateMemberTypePropertyTypeRequestModelFromJSONTyped(json, false);
}

export function UpdateMemberTypePropertyTypeRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMemberTypePropertyTypeRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'container': json['container'] == null ? undefined : ReferenceByIdModelFromJSON(json['container']),
        'sortOrder': json['sortOrder'],
        'alias': json['alias'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'dataType': ReferenceByIdModelFromJSON(json['dataType']),
        'variesByCulture': json['variesByCulture'],
        'variesBySegment': json['variesBySegment'],
        'validation': PropertyTypeValidationModelFromJSON(json['validation']),
        'appearance': PropertyTypeAppearanceModelFromJSON(json['appearance']),
        'isSensitive': json['isSensitive'],
        'visibility': MemberTypePropertyTypeVisibilityModelFromJSON(json['visibility']),
    };
}

export function UpdateMemberTypePropertyTypeRequestModelToJSON(json: any): UpdateMemberTypePropertyTypeRequestModel {
    return UpdateMemberTypePropertyTypeRequestModelToJSONTyped(json, false);
}

export function UpdateMemberTypePropertyTypeRequestModelToJSONTyped(value?: UpdateMemberTypePropertyTypeRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'container': ReferenceByIdModelToJSON(value['container']),
        'sortOrder': value['sortOrder'],
        'alias': value['alias'],
        'name': value['name'],
        'description': value['description'],
        'dataType': ReferenceByIdModelToJSON(value['dataType']),
        'variesByCulture': value['variesByCulture'],
        'variesBySegment': value['variesBySegment'],
        'validation': PropertyTypeValidationModelToJSON(value['validation']),
        'appearance': PropertyTypeAppearanceModelToJSON(value['appearance']),
        'isSensitive': value['isSensitive'],
        'visibility': MemberTypePropertyTypeVisibilityModelToJSON(value['visibility']),
    };
}

