/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateMediaTypeRequestModelAllowedMediaTypesInner } from './CreateMediaTypeRequestModelAllowedMediaTypesInner';
import {
    CreateMediaTypeRequestModelAllowedMediaTypesInnerFromJSON,
    CreateMediaTypeRequestModelAllowedMediaTypesInnerFromJSONTyped,
    CreateMediaTypeRequestModelAllowedMediaTypesInnerToJSON,
    CreateMediaTypeRequestModelAllowedMediaTypesInnerToJSONTyped,
} from './CreateMediaTypeRequestModelAllowedMediaTypesInner';
import type { CreateMediaTypeRequestModelCompositionsInner } from './CreateMediaTypeRequestModelCompositionsInner';
import {
    CreateMediaTypeRequestModelCompositionsInnerFromJSON,
    CreateMediaTypeRequestModelCompositionsInnerFromJSONTyped,
    CreateMediaTypeRequestModelCompositionsInnerToJSON,
    CreateMediaTypeRequestModelCompositionsInnerToJSONTyped,
} from './CreateMediaTypeRequestModelCompositionsInner';
import type { UpdateMediaTypeRequestModelPropertiesInner } from './UpdateMediaTypeRequestModelPropertiesInner';
import {
    UpdateMediaTypeRequestModelPropertiesInnerFromJSON,
    UpdateMediaTypeRequestModelPropertiesInnerFromJSONTyped,
    UpdateMediaTypeRequestModelPropertiesInnerToJSON,
    UpdateMediaTypeRequestModelPropertiesInnerToJSONTyped,
} from './UpdateMediaTypeRequestModelPropertiesInner';
import type { UpdateMediaTypeRequestModelContainersInner } from './UpdateMediaTypeRequestModelContainersInner';
import {
    UpdateMediaTypeRequestModelContainersInnerFromJSON,
    UpdateMediaTypeRequestModelContainersInnerFromJSONTyped,
    UpdateMediaTypeRequestModelContainersInnerToJSON,
    UpdateMediaTypeRequestModelContainersInnerToJSONTyped,
} from './UpdateMediaTypeRequestModelContainersInner';
import type { ReferenceByIdModel } from './ReferenceByIdModel';
import {
    ReferenceByIdModelFromJSON,
    ReferenceByIdModelFromJSONTyped,
    ReferenceByIdModelToJSON,
    ReferenceByIdModelToJSONTyped,
} from './ReferenceByIdModel';

/**
 * 
 * @export
 * @interface UpdateMediaTypeRequestModel
 */
export interface UpdateMediaTypeRequestModel {
    /**
     * 
     * @type {string}
     * @memberof UpdateMediaTypeRequestModel
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMediaTypeRequestModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMediaTypeRequestModel
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMediaTypeRequestModel
     */
    icon: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMediaTypeRequestModel
     */
    allowedAsRoot: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMediaTypeRequestModel
     */
    variesByCulture: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMediaTypeRequestModel
     */
    variesBySegment: boolean;
    /**
     * 
     * @type {ReferenceByIdModel}
     * @memberof UpdateMediaTypeRequestModel
     */
    collection?: ReferenceByIdModel | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMediaTypeRequestModel
     */
    isElement: boolean;
    /**
     * 
     * @type {Array<UpdateMediaTypeRequestModelPropertiesInner>}
     * @memberof UpdateMediaTypeRequestModel
     */
    properties: Array<UpdateMediaTypeRequestModelPropertiesInner>;
    /**
     * 
     * @type {Array<UpdateMediaTypeRequestModelContainersInner>}
     * @memberof UpdateMediaTypeRequestModel
     */
    containers: Array<UpdateMediaTypeRequestModelContainersInner>;
    /**
     * 
     * @type {Array<CreateMediaTypeRequestModelAllowedMediaTypesInner>}
     * @memberof UpdateMediaTypeRequestModel
     */
    allowedMediaTypes: Array<CreateMediaTypeRequestModelAllowedMediaTypesInner>;
    /**
     * 
     * @type {Array<CreateMediaTypeRequestModelCompositionsInner>}
     * @memberof UpdateMediaTypeRequestModel
     */
    compositions: Array<CreateMediaTypeRequestModelCompositionsInner>;
}

/**
 * Check if a given object implements the UpdateMediaTypeRequestModel interface.
 */
export function instanceOfUpdateMediaTypeRequestModel(value: object): value is UpdateMediaTypeRequestModel {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('allowedAsRoot' in value) || value['allowedAsRoot'] === undefined) return false;
    if (!('variesByCulture' in value) || value['variesByCulture'] === undefined) return false;
    if (!('variesBySegment' in value) || value['variesBySegment'] === undefined) return false;
    if (!('isElement' in value) || value['isElement'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    if (!('containers' in value) || value['containers'] === undefined) return false;
    if (!('allowedMediaTypes' in value) || value['allowedMediaTypes'] === undefined) return false;
    if (!('compositions' in value) || value['compositions'] === undefined) return false;
    return true;
}

export function UpdateMediaTypeRequestModelFromJSON(json: any): UpdateMediaTypeRequestModel {
    return UpdateMediaTypeRequestModelFromJSONTyped(json, false);
}

export function UpdateMediaTypeRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMediaTypeRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'],
        'allowedAsRoot': json['allowedAsRoot'],
        'variesByCulture': json['variesByCulture'],
        'variesBySegment': json['variesBySegment'],
        'collection': json['collection'] == null ? undefined : ReferenceByIdModelFromJSON(json['collection']),
        'isElement': json['isElement'],
        'properties': ((json['properties'] as Array<any>).map(UpdateMediaTypeRequestModelPropertiesInnerFromJSON)),
        'containers': ((json['containers'] as Array<any>).map(UpdateMediaTypeRequestModelContainersInnerFromJSON)),
        'allowedMediaTypes': ((json['allowedMediaTypes'] as Array<any>).map(CreateMediaTypeRequestModelAllowedMediaTypesInnerFromJSON)),
        'compositions': ((json['compositions'] as Array<any>).map(CreateMediaTypeRequestModelCompositionsInnerFromJSON)),
    };
}

export function UpdateMediaTypeRequestModelToJSON(json: any): UpdateMediaTypeRequestModel {
    return UpdateMediaTypeRequestModelToJSONTyped(json, false);
}

export function UpdateMediaTypeRequestModelToJSONTyped(value?: UpdateMediaTypeRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'allowedAsRoot': value['allowedAsRoot'],
        'variesByCulture': value['variesByCulture'],
        'variesBySegment': value['variesBySegment'],
        'collection': ReferenceByIdModelToJSON(value['collection']),
        'isElement': value['isElement'],
        'properties': ((value['properties'] as Array<any>).map(UpdateMediaTypeRequestModelPropertiesInnerToJSON)),
        'containers': ((value['containers'] as Array<any>).map(UpdateMediaTypeRequestModelContainersInnerToJSON)),
        'allowedMediaTypes': ((value['allowedMediaTypes'] as Array<any>).map(CreateMediaTypeRequestModelAllowedMediaTypesInnerToJSON)),
        'compositions': ((value['compositions'] as Array<any>).map(CreateMediaTypeRequestModelCompositionsInnerToJSON)),
    };
}

