/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserOrderModel = {
    UserName: 'UserName',
    Language: 'Language',
    Name: 'Name',
    Email: 'Email',
    Id: 'Id',
    CreateDate: 'CreateDate',
    UpdateDate: 'UpdateDate',
    IsApproved: 'IsApproved',
    IsLockedOut: 'IsLockedOut',
    LastLoginDate: 'LastLoginDate'
} as const;
export type UserOrderModel = typeof UserOrderModel[keyof typeof UserOrderModel];


export function instanceOfUserOrderModel(value: any): boolean {
    for (const key in UserOrderModel) {
        if (Object.prototype.hasOwnProperty.call(UserOrderModel, key)) {
            if (UserOrderModel[key as keyof typeof UserOrderModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserOrderModelFromJSON(json: any): UserOrderModel {
    return UserOrderModelFromJSONTyped(json, false);
}

export function UserOrderModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOrderModel {
    return json as UserOrderModel;
}

export function UserOrderModelToJSON(value?: UserOrderModel | null): any {
    return value as any;
}

export function UserOrderModelToJSONTyped(value: any, ignoreDiscriminator: boolean): UserOrderModel {
    return value as UserOrderModel;
}

