/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserKindModel = {
    Default: 'Default',
    Api: 'Api'
} as const;
export type UserKindModel = typeof UserKindModel[keyof typeof UserKindModel];


export function instanceOfUserKindModel(value: any): boolean {
    for (const key in UserKindModel) {
        if (Object.prototype.hasOwnProperty.call(UserKindModel, key)) {
            if (UserKindModel[key as keyof typeof UserKindModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserKindModelFromJSON(json: any): UserKindModel {
    return UserKindModelFromJSONTyped(json, false);
}

export function UserKindModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserKindModel {
    return json as UserKindModel;
}

export function UserKindModelToJSON(value?: UserKindModel | null): any {
    return value as any;
}

export function UserKindModelToJSONTyped(value: any, ignoreDiscriminator: boolean): UserKindModel {
    return value as UserKindModel;
}

