/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDataModel
 */
export interface UserDataModel {
    /**
     * 
     * @type {string}
     * @memberof UserDataModel
     */
    group: string;
    /**
     * 
     * @type {string}
     * @memberof UserDataModel
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof UserDataModel
     */
    value: string;
}

/**
 * Check if a given object implements the UserDataModel interface.
 */
export function instanceOfUserDataModel(value: object): value is UserDataModel {
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function UserDataModelFromJSON(json: any): UserDataModel {
    return UserDataModelFromJSONTyped(json, false);
}

export function UserDataModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDataModel {
    if (json == null) {
        return json;
    }
    return {
        
        'group': json['group'],
        'identifier': json['identifier'],
        'value': json['value'],
    };
}

export function UserDataModelToJSON(json: any): UserDataModel {
    return UserDataModelToJSONTyped(json, false);
}

export function UserDataModelToJSONTyped(value?: UserDataModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': value['group'],
        'identifier': value['identifier'],
        'value': value['value'],
    };
}

